feat: 파일 공유 메시지 저장 구현
woowacourse-teams/2022-pickpick pull request #225
Opened 2022-07-29 07:23 UTC by JangBomi

## 요약

파일 공유 메시지 저장 구현

<br><br>

## 작업 내용

- SlackEvent에 MESSAGE_FILE_SHARE 이벤트 추가
- MessageFileShareService 및 테스트 추가

<br><br>

## 참고 사항

- 텍스트 없이 파일을 공유할 때에라도, 빈 문자열로 저장하도록 구현했습니다
- 빈 문자열로 파일만 공유한 뒤에 추후 편집을 통해 메시지를 추가할 수 있기 때문입니다
- 이 경우, message_changed 이벤트에서 대응하려면 빈 텍스트라도 저장해둬야 해서 위와 같이 구현했습니다
- 다만, 메시지 조회 시점에 빈 문자열을 필터링해줘야 하는데, 이는 별도 태스크로 진행하겠습니다.

<br><br>

## 관련 이슈

- Close #224 

<br><br>

2022-07-29 07:23 UTC, JangBomi commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
> +    }
빈 문자열로 전달되어도 저장은 하도록 구현한 부분입니다

2022-07-29 10:39 UTC, hyewoncc approved these changes
프로그래밍 스타일이 점점 동기화(?)되어서 그런가 이번 PR에는 리뷰할게 크게 없네요! 
수고하셨고 `approve` 하겠습니다~

2022-07-29 10:39 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageFileShareServiceTest.java
> +    private Map<String, Object> fileShareRequest(String text) {
`💫final💫`

2022-07-29 10:39 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
> +    private static final String CHANNEL = "channel";
아래 사용처를 보니 "channel"로 꺼내오는 게 `channelSlackId`인 것 같아요 
좀 더 명확하게 상수명을 `CHANNEL_SLACK_ID`로 하는 건 어떨까요?

2022-07-29 10:45 UTC, yeon-06 requested changes
안녕하세요 리차드봄ㅎㅎ PR 잘 확인했습니다
FileShareService에 대해선 아직 궁금한 것이 남아 approve하지 않고 request changes로 코멘트 남겨두겠습니다
추가로 SlackEventTest와 MessageAcceptanceTest의 테스트 케이스도 추가해주시면 좋을 것 같아요~!
고생하셨습니다 😄

2022-07-29 10:45 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
> +    private SlackMessageDto convert(final Map<String, Object> requestBody) {
개인적으로는 메서드가 호출되는 순서로 정렬되는걸 선호하는 편입니다!
execute() 메서드에서 제일 먼저 호출되는 메서드가 convert()라서 execute() 바로 밑에 있으면 좋을 것 같아요😄

2022-07-29 10:45 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
> +        return SlackEvent.MESSAGE_CREATED == slackEvent;
```suggestion
        return SlackEvent.MESSAGE_FILE_SHARE == slackEvent;
```
file share enum이 따로 존재하는 것 같아요!!

2022-07-29 10:45 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
> +public class MessageFileShareService implements SlackEventService {
`MessageCreatedService` 클래스랑 거의 동일한 로직이 수행되고 있는 것 같아요🤔
`MessageCreateService`의 로직이 변한다면 `MessageFileShareService`의 로직도 변해야하는 완전 일치해야하는 케이스 같은데 혹시 클래스를 분리하신 이유가 있으실까요??
`isSameSlackEvent()`에서 아래와 같이 처리할 수도 있을 것 같아서요!!

```
return SlackEvent.MESSAGE_CREATED == slackEvent || SlackEvent.MESSAGE_FILE_SHARE == slackEvent;
```

2022-07-29 10:45 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
> +    }
이런 방식을 선택한 이유가 있을까요?
빈 문자열은 저장되지 않아도 된다고 생각해서요!

2022-07-29 10:52 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
> +    }
+ #225 이슈 방금 확인했네요 납득했습니다 👍

2022-07-29 15:44 UTC, HJ-Rich commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
> +public class MessageFileShareService implements SlackEventService {
파일 공유 메시지의 경우에는 
파일 공유 후 메시지 수정 이벤트도 같이 세심하게 살펴봐야하는 상황인 것 같습니다
해당 내용 구현을 진행한 뒤에 다시 리팩터링해봐야할 것 같은데요,

저는 완전히 동일한 내용이더라도 이벤트에 따라 구현체를 분리해두는게 더 좋지 않을까 하는 생각입니다.
일반론적인 설계 측면에서도 그러하다고 생각하고
현재 상황에서도 완전히 동일하더라도 다른 개발자들에게 분명한 메시지를 줄 수 있다고 생각합니다
클래스명이 MessageCreatedService 인데 둘을 모두 처리한다고 되어있으면 혼돈의 여지를 줄 수 있다고 느껴져서요.

이부분은 파일 공유 메시지 구현이 완료된 뒤 다시 살펴보도록 하겠습니다

2022-07-29 15:48 UTC, HJ-Rich commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
> +    private static final String CHANNEL = "channel";
써머의 의견에 일리가 있다고 느낍니다.

다만 그러한 변경을 진행한다면 일관성을 유지하기 위해
CLIENT_MSG_ID도 MESSAGE_SLACK_ID로, TIMESTAMP도 MESSAGE_POST_DATE로 
등등 모두 함께 변경되어야 하는 상황이고 모든 전략 구현체 내 선언도 변경되어야 한다고 생각합니다.

만약 위와 같은 변경에 모두가 동의한다면 그렇게 변경하는 것도 괜찮다고 생각합니다.

그러나 convert하는 시점에는 이게 이후에 어떤 값으로 사용되는지 보다도,
Map으로 전달된 RequestBody에서 어떠한 key로 값을 꺼내는지가 더 관심사라고 생각되어서
현재 구조를 유지하는 게 더 낫지 않을까 하는 생각입니다.

2022-07-30 07:06 UTC, HJ-Rich commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
> +    private static final String CHANNEL = "channel";
혹시 추가적으로 논의가 필요하다고 판단되실 경우 데일리 이후 백엔드 회의 때 안건으로 제시해주시면 감사하곘습니다

2022-07-30 07:08 UTC, HJ-Rich commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
> +public class MessageFileShareService implements SlackEventService {
이번 PR에서는 현 구조를 그대로 유지해두는 게 좋을 것 같다는 게 저희 페어 의견인데요,

우선은 추가 구현을 진행해서 파일 공유 후 메시지 편집을 통해 메시지를 추가하려는 상황에 대한 구현이 완료되면 그때 다시 살펴봐야할 것 같고요,

관련하여 보다 이르게 논의하고 싶으시다면 백엔드 회의 때 안건으로 제시해주시면 감사하겠습니다

2022-07-30 07:09 UTC, HJ-Rich commented
@yeon-06 피드백 반영 및 댓글로 의견 남겨두었습니다
다시 한 번 리뷰 부탁드립니다

2022-08-04 08:28 UTC, merged

2022-08-04 08:28 UTC, HJ-Rich commented
버전이 너무 뒤로 밀려서 브랜치 새로 생성해서 
SlackEventTest와 MessageAcceptanceTest 테스트 케이스 추가하겠습니다