feat: Calendar 컴포넌트 적용
woowacourse-teams/2022-pickpick pull request #251
Opened 2022-08-01 12:10 UTC by kkojae91

## 요약
Calendar 컴포넌트 적용

<br><br>

## 작업 내용
- usePortal custom hook 개발
- ISOConverter util 함수로 분리
- 기존 로직 usePortal custom hook으로 변경
- 기존로직에 Calendar component 적용

<br><br>

## 참고 사항

<img width="674" alt="image" src="https://user-images.githubusercontent.com/68001045/182144444-868fbba3-bd9d-4a33-a8b5-0049a57e8341.png">

<br><br>

## 관련 이슈

- Close #250 

<br><br>

2022-08-01 12:16 UTC, moonheekim0118 requested changes
다 좋습니다 !! 👍 👍 
다만, 캘린더 오픈되었을 때 overflow Y hidden 으로 수정부탁드립니다!!

2022-08-01 12:16 UTC, moonheekim0118 commented on frontend/src/components/Calendar/style.ts
> +  transform: translate(-50%, -50%);
CSS 천재에게 찾아가봅시다!!

2022-08-01 12:16 UTC, moonheekim0118 commented on frontend/src/hooks/usePortal.ts
> +export default usePortal;
💯 🥇 👍

2022-08-01 12:22 UTC, moonheekim0118 commented on frontend/src/@utils/index.ts
> +};
`T23:59:59` 가 반복되네요! 상수로 빼서 관리해도 좋을 듯합니다.
"오늘", "어제" 역시 상수로 빼서 관리하여 휴먼 에러를 방지해보아요

2022-08-01 12:22 UTC, moonheekim0118 commented on frontend/src/hooks/usePortal.ts
> +  };
요 부분 그냥 아이디어인데~
사용처에서 반환될 값들의 이름을 바꾸어야 할 경우가 많다면
객체가 아니라 배열로 반환하는건 어떤가요 ??  👀

2022-08-02 01:15 UTC, kkojae91 commented on frontend/src/hooks/usePortal.ts
> +  };
배열로 받게 될 경우 사용하지 않는 return 값을 _ 로 처리해야하는 부분이 있어 객체로 관리했어요!
예시는 아래 확인해주세요!
```
const [isPortalOpened, _, handleClosePortal, handleTogglePortal] = usePortal();
const { isPortalOpened, handleClosePortal, handleTogglePortal } = usePortal();
```

2022-08-02 01:48 UTC, kkojae91 commented on frontend/src/@utils/index.ts
> +};
상수처리 했습니다~

[d59aa44](https://github.com/woowacourse-teams/2022-pickpick/pull/251/commits/d59aa44f09edc127104086aa0fd2df80fd792000)

2022-08-02 01:48 UTC, moonheekim0118 approved these changes

2022-08-02 01:48 UTC, moonheekim0118 commented on frontend/src/@utils/index.ts
> +
상수화! 좋아요

2022-08-02 01:49 UTC, merged