feat: 북마크 조회 기능 구현
woowacourse-teams/2022-pickpick pull request #257
Opened 2022-08-02 05:44 UTC by yeon-06

## 요약
북마크 조회 기능 구현
<br><br>

## 작업 내용
- 북마크 조회 기능 구현
- 북마크 생성 서비스 테스트 보완

<br><br>

## 관련 이슈

- #248 

<br><br>

2022-08-02 11:18 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/message/application/BookmarkService.java
> +                .limit(20)
셀프 리뷰..😅 
상수 처리 또는 RequestParam으로 받게 하는 로직 필요

2022-08-02 11:44 UTC, HJ-Rich requested changes
복잡한 로직인데 빠르게 구현하셨네요. 
훌륭하십니다.
감사합니다.

구두로 전달드린 것과 같이 
일부 로직상 수정이 필요한 부분이 있는 것 같습니다.
테스트 코드는 로직 수정 이후에 리뷰 재요청해주시면 그때 확인하겠습니다.

다시 한 번 노고에 감사드립니다

2022-08-02 11:44 UTC, HJ-Rich commented on backend/src/main/java/com/pickpick/message/application/BookmarkService.java
> +        List<Bookmark> foundBookmarks = jpaQueryFactory
bookmarkId가 있거나 없거나 라는 두 가지 경우의 수만 존재한다면,
Repository 내 메서드 선언을 통해 분기처리를 하면 어떨까 하는 생각도 드는데요,

@Query("jpql") 이 다소 꺼려진다는 점이 이슈네요
저는 이참에 Query 애너테이션과 jpql 작성을 통한 Repository 내 메서드 선언을
한 번 경험해보고 싶다는 생각도 들지만 현재 구조도 훌륭하다고 생각합니다.

추후 Repository 내 Query Method 양식대로 작성하면서도
Fetch Join 이슈와 Limit 이슈를 모두 핸들링할 수 있는 방법을 찾아낸다면
그때 리팩터링 해봐도 좋을 것 같습니다.

2022-08-02 11:44 UTC, HJ-Rich commented on backend/src/main/java/com/pickpick/message/application/BookmarkService.java
> +        return foundBookmarks;
북마크 응답 시, 메시지 작성 시간 내림차순 정렬해서 응답해야 하는 것으로 전달 받았습니다.

즉, 최초 북마크 화면에 진입 시, 북마크로 등록된 메시지들 중
가장 최근에 작성된 메시지가 맨 위에 노출되어야 한다는 의미입니다.

이 경우, limit 하기 전에 정렬을 desc로 정렬한 뒤 limit을 적용해야할 것 같습니다.
또한, limit 하기 전에 이미 정렬을 desc로 하고 limit을 한다면,
reverse등의 java 애플리케이션 내 재정렬은 불필요할 것 같습니다.

2022-08-02 11:44 UTC, HJ-Rich commented on backend/src/main/java/com/pickpick/message/application/BookmarkService.java
> +    }
북마크 아이디가 전달되는 경우는 아래로 스크롤하는 케이스만 존재하는데요,
이 경우, 해당 메시지 작성시간 보다 과거에 작성된 내용을 조회해야 하기 때문에
before 조건으로 BooleanExpression을 반환해야할 것 같습니다.

2022-08-02 11:44 UTC, HJ-Rich commented on backend/src/main/java/com/pickpick/message/application/BookmarkService.java
> +    }
아래로 가는 시나리오만 있기 때문에,
무조건 시간 내림차순으로 정렬하고, 맨 뒤에 있는게 가장 과거이기 때문에,
이것보다 더 과거(before)인 게 있는지 검증하는 조건이 되어야할 것 같습니다.

2022-08-02 11:44 UTC, HJ-Rich commented on backend/src/main/java/com/pickpick/message/ui/dto/BookmarkResponse.java
> +    }
빌더 패턴을 사용해보면 어떨까요?

2022-08-02 11:49 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/message/application/BookmarkService.java
> +                .limit(20)
상수 처리 완료

2022-08-02 13:14 UTC, JangBomi approved these changes
리차드가 리뷰 꼼꼼히 남겨줬어서 제가 크게 확인할 부분이 없네요..!
저는 approve 하겠습니다 :)

2022-08-02 13:14 UTC, JangBomi commented on backend/src/main/java/com/pickpick/message/application/BookmarkService.java
> +        }
로직 이해가 안가서 질문 드립니다! 혹시 bookmarkId가 null인 경우는 어떤 경우에 발생하나요??

2022-08-02 13:14 UTC, JangBomi commented on backend/src/main/java/com/pickpick/message/ui/dto/BookmarkResponse.java
> +    }
깔끔해요 굿..!

2022-08-02 13:14 UTC, JangBomi commented on backend/src/test/java/com/pickpick/acceptance/BookmarkAcceptanceTest.java
> +    }
```suggestion
    private List<Long> convertToIds(final BookmarkResponses response) {
        return response.getBookmarks()
        .stream()
        .map(BookmarkResponse::getId)
        .collect(Collectors.toList());
    }
```

tc이긴 하지만 개행을 추가하는건 어떨까요?

2022-08-02 13:14 UTC, JangBomi commented on backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
> +        return response.getBookmarks().stream().map(BookmarkResponse::getId).collect(Collectors.toList());
위의 convertToIds와 동일하게 개행 추가 어떨까요?

2022-08-02 15:15 UTC, HJ-Rich commented on backend/src/main/java/com/pickpick/message/ui/dto/BookmarkResponse.java
> +    }
실수를 방지할 수 있는 훌륭한 변화네요

2022-08-03 01:08 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/message/application/BookmarkService.java
> +        }
처음에 북마크 화면에 진입하는 경우에는 bookmarkId에 아무런 값도 보내주지 않습니다!😄 (=null 값으로 들어옴)

2022-08-03 01:32 UTC, merged