feat: 인증 인가 및 로그아웃 기능
woowacourse-teams/2022-pickpick pull request #262
Opened 2022-08-02 07:28 UTC by moonheekim0118

## 요약

인증 인가 및 로그아웃 기능

## 작업 내용
- 로그인 여부 확인(인증) API 모킹 (/api/auth)
- PrivateRouter, PublicRouter 구현
- 랜딩페이지에서 Navigation Bar 제거

<br><br>

## 참고사항
- 추후 스낵바 status 추가 필요

<br><br>

## 관련 이슈

- Close #160 

<br><br>

2022-08-02 08:02 UTC, moonheekim0118 commented on frontend/src/components/PrivateRouter/index.tsx
> +      useErrorBoundary: false,
`useErrorBoundary: false` 옵션을 주지 않으면
모든 API 에러가 에러바운더리로 넘어가요!!

2022-08-02 08:02 UTC, moonheekim0118 commented on frontend/src/components/@layouts/Navigation/index.tsx
> +
스크롤을 사라지게하고, 다시 띄워주는 로직이 계속 반복되는데 ~ 어떻게 반복을 줄일 수 있을까요 ?!? 👀 아이디어를 주세요!!

2022-08-02 10:20 UTC, kkojae91 requested changes
소소한 질문과 제안 남겼어요! 확인 해주세용~! 👍🏼 수고하셨어요!

2022-08-02 10:20 UTC, kkojae91 commented on frontend/src/hooks/useAuthentication.ts
> +    setCookie(ACCESS_TOKEN_KEY, "test");
Mutation 저도 확인하고 다른 곳에 적용해볼게요!

2022-08-02 11:22 UTC, moonheekim0118 commented on frontend/src/components/PrivateRouter/index.tsx
> +export default PrivateRouter;
저는 개인적으로 HOC 방법보다 컴포넌트 합성을 선호하긴 하는데요, 그 이유가 HOC 는 결국 클래스형 컴포넌트의 잔재라고 생각하기도 하고, 읽기도 어렵다고 생각해서였어요!
그리고 PrivateRouter 와 PublicRouter 를 굳이 분리한 이유는, 두가지의 역할이 매우 다르다고 생각했기 때문입니다!
물론 '인가'의 역할을 하는것은 같지만, 두 역할 (인증 된 사용자인지 / 인증되지 않은 사용자인지)을 하나의 컴포넌트에 묶어두면, 컴포넌트가 매우 복잡해지고 나중에 읽기 어렵더라구요. 이 부분 더 이야기 나누어보아요.

2022-08-02 11:23 UTC, moonheekim0118 commented on frontend/src/pages/index.tsx
> +        <Component {...props} />
💦

2022-08-02 12:46 UTC, moonheekim0118 commented on frontend/src/@utils/index.ts
> +    )
일단 동작하는 정규식 막 같다붙였네요 😓
짚어주셔서 감사합니다! 
더 간결한 정규식으로 바꾸었습니다.
```
 new RegExp(`(?<=${key}=)[^;]*`); 
```
해당 정규식은 key(좌항)의 우항에 value를 '='와 세미콜론 제외하고 가져오는 정규식입니다. 
일단, 해당 정규식의 역할을 주석으로 남겨놓았어요.
혹시몰라서 출처도 아래 첨부할게요!
[c0533df](https://github.com/woowacourse-teams/2022-pickpick/pull/262/commits/c0533df8b6f44d63078bfc5f034088f5060fb1d2)


- [출처](https://www.codegrepper.com/code-examples/javascript/get+cookie+by+name+javascript)

2022-08-03 03:51 UTC, kkojae91 commented on frontend/src/components/@layouts/Navigation/index.tsx
> +
요건 제가 리팩터링 하면서 확인 한 번 해볼게요!!!

2022-08-03 03:55 UTC, kkojae91 commented
고생하셨어요 호프~~

2022-08-03 03:55 UTC, merged