feat: 메시지 리마인더 조회 api 구현
woowacourse-teams/2022-pickpick pull request #366
Opened 2022-08-09 07:16 UTC by JangBomi

## 요약

메시지 리마인더 조회 api 구현
<br><br>

## 작업 내용

- 메시지 리마인더 조회 api 구현
- 인수테스트, 서비스테스트, 컨트롤러 테스트 작성
- 리마인더 조회 api에 대해 RestDocs 만들어지도록 문서 수정

## 관련 이슈

- Close #365

<br><br>

2022-08-09 07:19 UTC, JangBomi commented on backend/src/main/java/com/pickpick/message/application/ReminderService.java
> +        }
과거 리마인더를 알려줄 필요가 없어서 현재 시간(LocalDateTime.now()) 기준으로 조회를 했는데, 테스트 시 문제가 발생할 예정입니다.
현재 테스트 픽스처들이 2022-8-12로 되어있어서 오늘(8/9)일에 테스트를 실행하면 문제가 없지만, 8월 13일에 테스트를 실행하면, 테스트가 실패할 예정입니다.(테스트가 시간에 종속적입니다)

어떻게 해결하면 좋을까요? 리차드와 써머의 지혜가 필요해요 🧐

2022-08-09 07:47 UTC, hyewoncc requested changes
빠른 구현 꼼꼼한 테스트에 레닥 작성까지 수고했어요👍  
코드 스타일 관련은 의견이 일치하는 것만 반영해주세요!  

리마인더 생성 시 유효한 시간 검증은 필요할 것 같아서 일단 `request changes`로 남길게요  
수정 후에 `approve`와 별도로 알아서 머지하셔도 괜찮습니다!!

2022-08-09 07:47 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/application/ReminderService.java
> +
💄 빈 줄이 두개네요~

2022-08-09 07:47 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/ui/ReminderController.java
> +
💄 빈 줄이 두줄!!

2022-08-09 07:47 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
> +        System.out.println(LocalDateTime.now());
테스트 실행 시 콘솔 내에서 현재 시간을 보기 위함일까요?  
아니면 삭제를 깜빡하신걸까요? 👀

2022-08-09 07:47 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
> +        assertThat(convertToIds(reminderResponses)).containsExactlyElementsOf(expectedIds);
서비스 테스트에서는 `assertAll`로 묶었는데 인수 테스트에서는 별개로 쓰셨네요  
이유가 있을까요?  
단순 질문이고 이유가 있다면 통일하지 않으셔도 괜찮습니다!!

2022-08-09 07:47 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/domain/Reminder.java
> +        this.remindDate = remindDate;
리마인더를 생성할 때 `과거 시간`을 설정하는 경우 예외 처리를 하는 건 어떨까요?  
프론트에서 과거로 갈 수 없게 처리해줄 것 같긴 하지만 백에서도 확인이 필요한 규칙이라 생각해요

2022-08-09 07:47 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/ui/dto/ReminderResponse.java
> +                            final LocalDateTime remindDate) {
파라미터 줄바꿈 기준이 있었을까요?! ㅎㅎ  
맥락별(?)로 나눈 거라면  

```
final Long id, final Long messageId, 
final String username, final String userThumbnail, final String text,
```

이렇게는 어떠세요?

2022-08-09 07:52 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/application/ReminderService.java
> +        }
@.@ ...

2022-08-09 08:01 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/application/ReminderService.java
> +        }
당장은 또동차, 또또 랜덤 테스트처럼 `기준(=현재) 시각을 제공하는 객체를 인터페이스로 분리`밖에 떠오르지 않네요... 
이름 막 짓자면 `TimeSetter` 라는 클래스 안에 `now()' 메서드를 만들어서  

1. 프로덕션에서는 `LocalDateTime.now()`를 반환
2. 테스트에서는 `2022-08-12 00:00:00`의 고정시를 반환  

이렇게 하면 테스트 시각을 고정할 수 있을 것 같아요  
다만 테스트만을 위해서 이렇게 분리해야 할까? 싶으면서도 리마인더 도메인의 시간에 종속정인 특수성을 생각하면 이렇게 해서라도 테스트를 하는 게 좋다고 느껴집니다

2022-08-09 08:22 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
> +        System.out.println(LocalDateTime.now());
LocalDateTime.now()를 이렇게 저렇게 모킹 시도해보느라 생겼던 코드인데요
삭제.. 깜빡한게 맞습니다... 감사합니다😂

2022-08-09 08:23 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/message/ui/dto/ReminderResponse.java
> +                            final LocalDateTime remindDate) {
자동 정렬을 사용한건데 왜 이러한 기준으로 나눈건지는 모르겠네요🤔
한 줄로 만든 뒤 자동 정렬을 다시 시켜볼게요!

2022-08-09 08:53 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
> +        assertThat(convertToIds(reminderResponses)).containsExactlyElementsOf(expectedIds);
딱히 이유는 없습니다! 적용하겠습니다~

2022-08-09 09:16 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/message/application/ReminderService.java
> +        }
+ [속닥속닥팀의 해결방법](https://velog.io/@betterfuture4/%EC%86%8D%EB%8B%A5%EC%86%8D%EB%8B%A5-%ED%83%80%EC%9E%84%EB%A8%B8%EC%8B%A0-%ED%85%8C%EC%8A%A4%ED%8A%B8-%ED%95%98%EA%B8%B0feat.LocalDateTime.nowclock)

2022-08-09 18:29 UTC, HJ-Rich requested changes
정말 고생 많으셨습니다.

논의해봐야할 부분이 있는 것 같아 Request Changes로 남겨두겠습니다.

내일 오전중에 짧게 논의하여 결정될 수 있는 사안이라 작업에 지연이 발생하지는 않을 것 같습니다.

그 결정에 따라서 변경이 필요 없는 것으로 정해진다면
Approve로 받아들여서 직접 merge해주셔도 될 것 같습니다. 

정말 고생 많으셨습니다.
감사합니다.

2022-08-09 18:29 UTC, HJ-Rich commented on backend/src/main/java/com/pickpick/message/application/ReminderService.java
> +        }
리마인더 설정했던 시간 보다 미래 시점이 되면
그때부턴 리마인더 설정했던 메시지가 알림 목록에서 자동으로 사라지겠군요.

리마인더 설정했던 시간이 지나더라도
리마인더 비활성화 상태로 남아서 다시 리마인더 설정할 수 있게
하는 기능을 제공하는 건 어떨까요?

아래와 같은 장점이 있을 것 같아서요.

- 사용자 경험이 증대된다.
  - 리마인더 경과 여부를 알려줄 수 있다.
  - 리마인더 설정했던 메시지들을 계속 보여줄 수 있다.
  - 경과된 리마인더를 재설정하게 해줄 수 있다.
- 61번 라인에서 now 없이 null을 반환할 수 있게 된다.
- DB에 적재되는 경과된 리마인더에 대해 처리를 고려하지 않아도 된다.
  - 사용자가 직접 삭제 요청을 해서 삭제할 수 있기 때문이다.

추가로 개인적인 의견입니다.
동적 조건이 하나만 있다면 QueryMethod를 이용해서 단순 Repository 메서드 선언으로
처리하는 게 어떨까 하는 생각이 있는데
이 부분은 지난번에도 무언가 기술적 문제로 이후로 미룬 바 있어요.
아마 레벨4때 시도해볼 수 있을지도 모르겠는데
상기하고자 하는 의미에서 그냥 한 번 더 언급해봅니다.

2022-08-09 18:29 UTC, HJ-Rich commented on backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
> +class ReminderServiceTest {
DataJpaTest + Import를 사용해보면 어떨까요? 
서비스 테스트에선 SpringBootTest가 불필요하지 않나 하는 생각입니다.

https://github.com/woowacourse-teams/2022-pickpick/pull/358/files#r940042839

2022-08-10 01:23 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/message/application/ReminderService.java
> +        return new ReminderResponses(toReminderResponseList(reminderList), isLast(reminderList, memberId));
저는 개인적으로 빌더 패턴을 좋아하지 않는데요
모든 값을 넣어야하는 상황에서 일부만 값을 넣어도 잘 생성되기 때문입니다🙂

이전에 다른 PR에서 builder 패턴의 적용을 받아들인건 String과 Long형 타입을 생성자에서 여러개 받고 있기 때문에 헷갈릴 여지가 크다 생각했기 때문인데요!
현재는 List와 boolean이니 헷갈릴 일이 없다고 생각해요~

2022-08-10 01:25 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/message/application/ReminderService.java
> +        }
리마인더 시간에 대한건 회의 때 이야기 해봅시다!
QueryDSL을 사용한 이유는 저는 메시지, 북마크 기능을 개발했으나 봄이 다뤄본 적이 없는 기술이기 때문에 적용해보았습니다 ㅎ_ㅎ
일단 QueryDsl 사용 자체에 대해 다시 생각해보아야하니 이 건도 보류할게요~

2022-08-10 02:47 UTC, JangBomi commented on backend/src/main/java/com/pickpick/message/application/ReminderService.java
> +        }
/api/messages 에서 메시지 불러올 때 이미 시간 지난 메시지라면 알람설정 색 없어지게 수정해야함

2022-08-10 02:50 UTC, HJ-Rich commented on backend/src/main/java/com/pickpick/message/application/ReminderService.java
> +        }
리마인더 경과된 데이터는 바로 사라지게 하는 걸로 결정돼서
Approve 하겠습니다~

2022-08-10 02:50 UTC, HJ-Rich approved these changes

2022-08-10 04:25 UTC, JangBomi commented on backend/src/main/java/com/pickpick/message/application/ReminderService.java
> +    public static final int COUNT = 20;
DEFAULT_LIMIT_COUNT와 COUNT가 의미하고자 하는게 동일한 것 같아요. 북마크의 컨벤션을 따라 현행 COUNT로 유지하겠습니다!

2022-08-10 04:30 UTC, HJ-Rich commented on backend/src/main/java/com/pickpick/message/application/ReminderService.java
> +        return new ReminderResponses(toReminderResponseList(reminderList), isLast(reminderList, memberId));
모든 값이 들어왔을 때에만
build 메서드가 수행될 수 있게
생성자 내부에서 검증을 해줄 수 있을 것 같아요

그러면 처음 보는 사람에게도 더 보기 좋은 코드가 될 수 있을 것 같아요

그치만 어찌 보면 사소한 내용인 것 같습니다 ㅎ

2022-08-10 04:31 UTC, HJ-Rich commented on backend/src/main/java/com/pickpick/message/application/ReminderService.java
> +    public static final int COUNT = 20;
처음 보는 사람에게 COUNT와 DEFAULT LIMIT COUNT가 같은 의미로 전달되지는 않을 것 같다는 생각이에요

그러나 그리 중요한 건 아닌 것 같습니다
현행 유지 좋습니다~!

2022-08-10 04:49 UTC, hyewoncc approved these changes

2022-08-10 05:20 UTC, JangBomi commented
아직 수정중이에요

2022-08-10 10:22 UTC, merged