feat: 검색 기능 API 연동 및 SearchResult Page 개발
woowacourse-teams/2022-pickpick pull request #371
Opened 2022-08-09 15:26 UTC by kkojae91

## 요약
검색 기능 API 연동 및 SearchResult Page 개발

<br><br>

## 작업 내용
- useChannelIds hook 네이밍 변경 -> useSelectChannels
- SearchForm component 개발
- SearchInput, SearchOptions button type 설정 및 스타일 변경
- SearchForm component Feed, SpecificDateFeed page component에 적용
- SearchResult component Routes 연결 및 PATH_NAME 상수화
- getMessages API 명세에 맞게 keyword 추가
- convertSeparatorToKey util 함수 작성
- SearchResult page component 개발
- useModal hook useEffect clean up callback 함수 작성
    - scroll hidden -> auto 로 변경하는 clean up callback 함수 작성
- useSearchKeywordForm custom hook 으로 form 관련 로직 분리

<br><br>

## 참고 사항

이야기 했던 것 처럼 기존에 SearchInput, SearchOptions로 구성되어 있던 것을 SearchForm Component로 추출 후 API 연동을 진행했습니다.
SearchResult page Component를 생성했으니 확인해주시면 감사하겠습니다.

이슈를 따로 만들까 하다 이번 커밋에 useModal hook안에 useEffect clean up 함수가 작성되어 있지 않아 스크롤이 고장나는 이슈가 있어 clean up 함수 작성해서 해결했어요.

확인하고 리뷰 남겨주세요~! 😊

<br><br>

## 관련 이슈

- Close #369 

<br><br>

2022-08-09 18:17 UTC, moonheekim0118 requested changes
구현해주신것 잘 확인했어요!
<img width="1292" alt="스크린샷 2022-08-10 오전 2 52 36" src="https://user-images.githubusercontent.com/61469664/183729189-b4940d4f-e4ec-4911-938c-227902332e6c.png">
다만 z index 가 깨져서 이런 UI 깨짐이 있어요 흑흑

그리고, 저희가 날짜 드롭다운도 그랬고, 이번에 채널옵션 선택하는 컴포넌트도 
`외부 영역이 클릭되면 닫혀아해서` Dimmer + useModal 을 어쩔 수 없이 써야 했던 것 같아요.
그런데 이러면...현재 날짜 드롭다운 클릭했을 때나, Search Input 이 focus 되었을 때 스크롤바가 사라진다는 문제점이 있네요 (완전히..간과했음 흑흑)

이 부분 어떻게 수정할지 같이 고민해보아요.
지금 떠오르는 방안은.

1. useModal 말구 새로운 커스텀훅을 만들어준다. (스크롤이 사라지지 않는)
2. 바깥 영역에 이벤트를 걸어준다. (마냥 안좋은 방법이라구 생각했는데, 이게 대표적인 해법이긴하더라구요)

제가 2번 해결방법이 궁금해서 찾아봤는데 예전에 [jsConf](https://www.youtube.com/watch?v=J-g9ZJha8FE&t=481s) 에서 발표된 `useOuterClick` 훅이 있대요 이런 식으로 만들어서 outside 영역이 클릭되었을 때 닫히게하는 핸들러함수를 넘겨주는 방식으로 구현할 수도 있겠어용
```jsx
function useOuterClick(callback) {
  const innerRef = useRef();
  const callbackRef = useRef();

  // set current callback in ref, before second useEffect uses it
  useEffect(() => { // useEffect wrapper to be safe for concurrent mode
    callbackRef.current = callback;
  });

  useEffect(() => {
    document.addEventListener("click", handleClick);
    return () => document.removeEventListener("click", handleClick);

    // read most recent callback and innerRef dom node from refs
    function handleClick(e) {
      if (
        innerRef.current && 
        callbackRef.current &&
        !innerRef.current.contains(e.target)
      ) {
        callbackRef.current(e);
      }
    }
  }, []); // no need for callback + innerRef dep
  
  return innerRef; // return ref; client can omit `useRef`
}
```

2022-08-09 18:17 UTC, moonheekim0118 commented on frontend/src/pages/SearchResult/index.tsx
> +
이 부분 제 PR 머지되면 필요없는 부분이라 제거해주시면 감사하겠습니닷!!

2022-08-09 18:17 UTC, moonheekim0118 commented on frontend/src/hooks/useModal.ts
> +    };
![IMG_0874](https://user-images.githubusercontent.com/61469664/183726633-327e4ee5-3461-487a-b790-5b326c63dbbc.JPG)

제대로 간과했네요...추가해주셔서 감사합니다..ㅎ

2022-08-09 18:17 UTC, moonheekim0118 commented on frontend/src/components/Drawer/style.ts
> +  z-index: 1;
Drawer 에 z index 를 추가해야했던 이유가 있을까요??

2022-08-09 18:17 UTC, moonheekim0118 commented on frontend/src/pages/SearchResult/index.tsx
> +}
검색 결과 없을 때 상태 추가해주세용! EmptyStatus 그대로 사용하면 될 것 같습니다 :)

2022-08-09 22:14 UTC, moonheekim0118 commented on frontend/src/pages/SearchResult/index.tsx
> +
이 부분 제 pr 머지되면 사라질 부분이라서 삭제해주셔도 될 것 같습니다 :)

2022-08-10 04:20 UTC, kkojae91 commented on frontend/src/components/Drawer/style.ts
> +  z-index: 1;
이 부분은 약간 응급 처치... 한다고 넣어놓은 건데 다른 문제들도 있는 것 같아서 다시 한 번 정리해야할 것 같아요!
이따 회의때 추가로 이야기해봐요!

2022-08-10 04:33 UTC, kkojae91 commented on frontend/src/Routes.tsx
> +      },
넵 그렇네요!! 반영 했습니다. [a834309](https://github.com/woowacourse-teams/2022-pickpick/pull/371/commits/a8343098c9ea9ddaae0eea59efa91a322dec8f06)

2022-08-10 04:34 UTC, kkojae91 commented on frontend/src/pages/SearchResult/index.tsx
> +
넵~! 반영했어요~ 
d2c0baf

2022-08-10 05:23 UTC, moonheekim0118 approved these changes
수고하셨습니당 ~! 논의된 부분은 같이 리팩터링해용~! 👍

2022-08-10 05:23 UTC, merged