feat: 리마인더 요청 모달창 UI 구현
woowacourse-teams/2022-pickpick pull request #409
Opened 2022-08-13 10:43 UTC by kkojae91

## 요약
리마인더 요청 모달창 UI 구현
<br><br>

## 작업 내용

- getTimeStandard util 함수명 변경 및 리턴 벨류 변경
- Calendar svg 이미지 assets에 추가
- ReminderModal component 개발
- useReminderModal custom hook 개발
- Feed, SpecificDateFeed component에 ReminderModal Component 적용
- ReminderModalOptions, ReminderModalToggleDropdown component 분리

<br><br>

## 참고 사항

UI 구현은 모두 완료가 되었고, 코드가 다소 지저분해 진 경향이 있네요... 추가 리펙터링 및 함수명 재설정 해야하는 부분들이 존재하는 것 같아요.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/68001045/184480127-3d8420de-2f40-4322-b634-c7bbca9ed265.png">

<img width="376" alt="image" src="https://user-images.githubusercontent.com/68001045/184480136-8a52a644-3e74-4088-8331-5e609f154b94.png">

<img width="374" alt="image" src="https://user-images.githubusercontent.com/68001045/184480144-a528a574-4d12-404d-b640-59e0404a6f52.png">

<br><br>

## 관련 이슈

- Close #393 

<br><br>

2022-08-13 19:21 UTC, moonheekim0118 requested changes
정말 고생많으셨네요. 코드만 봐도 UI 가 얼마나 구현하기 복잡했는지 느껴져요 ㅠ-ㅠ
리뷰 좀 많이 남겼는데 천천히 반영해주시구 몇가지는 다음 api 연동할때 같이 가져가도 좋을 것 같아요.

그리고, 리뷰하다가 문득 든 생각인데 모달 안에서 snackBar 를 띄워줄 일이 생길 것 같은데..그러면 Portal 을 하나만 사용하는게 문제가 될 수도 있을 것 같아요.
그래서 제안드리는건데 snackBar 용 포탈만 따로 만드는거 어떠신가요?
모달들은 서로 겹쳐서 열릴 일이 없지만 snackbar 는 모달 위에 열릴 일이 있을 것 같아요 ~! 허허

아무튼 너무너무 고생하셨습니다! 👍

2022-08-13 19:21 UTC, moonheekim0118 commented on frontend/src/components/ReminderModal/index.tsx
> +
혹시 `handleOpenDropdown ` 을 꼭 해주어야 하는 이유가 있을까요?
아무리 눈 부릅뜨고 찾아봐도 useReminderModal 에서 정의한 `isDropdownOpened` 상태를 사용하지 않는 것 같아요.
아예 useReminderModal 에서 isDropdownOpened, handleDropdown 관련 로직이 없어도 될 것같은데!
혹시 제가 놓친부분이 있을까요 ??

2022-08-13 19:21 UTC, moonheekim0118 commented on frontend/src/components/ReminderModalOptions/index.tsx
> +function ReminderModalOptions({
음 네이밍이 ReminderModalOptions 라고하니까 모달의 켜짐/꺼짐 옵션 같네요!
그것보다는 Reminder 내부에 있는 시간 관련 Option 이니까 더 명확하게 가져가보는거 어떨까요?
`TimePicker` - 시간 선택자 
혹은
`TimePickerOptions`- 시간 선택자 옵션 
는 어떠신가요?
Meterial Design 에서도 Time Picker 라고 쓰는 것 같아요

https://material.io/components/time-pickers#anatomy

2022-08-13 19:21 UTC, moonheekim0118 commented on frontend/src/components/ReminderModalOptions/index.tsx
> +            {isPadStart ? optionText.padStart(3, "0") : optionText}
padStart 관련 로직은 util 로 따로 빼주는건 어떨까요??

2022-08-13 19:21 UTC, moonheekim0118 commented on frontend/src/hooks/useReminderModal.ts
> +  const { year, month, date, hour, minute } = getDateInformation(new Date());
훅 이름도 조금 더 명확하게 가져가보는거 어떠신가요?
이 훅이 하는 일이 사실 Reminder 를 셋팅하고 컨트롤하는거지, Reminder Modal 을 컨트롤하는건 아니니까 아예 `useReminder` , 
'useSetReminder' 정도는 어떨까요 ?ㅅ?

2022-08-13 19:21 UTC, moonheekim0118 commented on frontend/src/components/ReminderModalToggleDropdown/index.tsx
> +  handleToggleDropdown,
이거 리마인더에 있는
날짜 선택 옵션 드랍다운/  시간 선택 옵션 드랍다운 오픈(토글) 해주는 토글러 인것같은데 네이밍 더 명확하게 가져가봐요!

`TimePickerToggler` 혹은 `ReminderTimePickerToggler` 는 어떠신가요  ?
아까 위에서 봤던 `TimePicker` 랑 통일되면 좋겠네요!

2022-08-13 19:32 UTC, moonheekim0118 commented on frontend/src/components/ReminderModalOptions/index.tsx
> +  isPadStart,
사소하지만 `isPadStart` 보다 , 해당 컴포넌트의 사용처에서는 props 를 통해서  padStart 인지 여부를 확인하는거니까
`needPadStart` 어떤가요? ㅎ

2022-08-13 19:32 UTC, moonheekim0118 commented on frontend/src/hooks/useReminderModal.ts
> +
굳이 year.toString() 을 해줘야하는 이유가 있을까요?
어차피 `${}` <- 요기 안에 들어가면 Number 가 string 으로 변환될텐데
뭔가 의도하신게 있으실까요?

2022-08-13 19:32 UTC, moonheekim0118 commented on frontend/src/hooks/useReminderModal.ts
> +  );
여기도 문자열로 변환을 해주신 이유가 궁금합니다

2022-08-13 19:45 UTC, moonheekim0118 commented on frontend/src/hooks/useReminderModal.ts
> +  const lastDate = new Date(year, month, 0).getDate();
lastDate 구하는 로직도 따로 유틸로 빼놔도 괜찮겠네요! 혼자 new Date 생성하고..getDate 메서드 호출하니까 어색해보여요

2022-08-13 19:51 UTC, moonheekim0118 commented on frontend/src/components/ReminderModalOptions/index.tsx
> +  handleChangeText: (event: ChangeEvent<HTMLInputElement>) => void;
리액트에서 제공해주는 ChangeEventHandler 타입이 있어요! 이걸로 바꿔도 될 듯싶네요! 저도 오늘 알앗어요 ㅎㅎ 

```suggestion
  handleChangeText: ChangeEventHandler<HTMLInputElement>
```

2022-08-14 05:36 UTC, kkojae91 commented on frontend/src/hooks/useReminderModal.ts
> +  };
이부분은 API 연동 하면서 제거할게요~!

2022-08-14 05:36 UTC, kkojae91 commented on frontend/src/hooks/useReminderModal.ts
> +    }
넵 API 연동 하면서 스넥바로 대체 하려고 생각중입니다~!

2022-08-14 05:37 UTC, kkojae91 commented on frontend/src/hooks/useReminderModal.ts
> +      Number(checkedMinute) < minute
좋은 아이디어네요! 반영하도록 할게요~!

2022-08-14 05:37 UTC, kkojae91 commented on frontend/src/hooks/useReminderModal.ts
> +  }
좋네요!! 반영하도록 할게요~!

2022-08-14 05:38 UTC, kkojae91 commented on frontend/src/hooks/useReminderModal.ts
> +
좋은 생각이네요~! 적용하도록 할게요!

2022-08-14 05:42 UTC, kkojae91 commented on frontend/src/hooks/useReminderModal.ts
> +
기존 로직에서 리펙터링하다 놓친 부분이네요!! toString()은 빠져도 될 것 같아요! 반영하도록 할게요~!

2022-08-14 05:44 UTC, kkojae91 commented on frontend/src/components/ReminderModalOptions/index.tsx
> +  isPadStart,
조금 더 명시적으로 needZeroPaddingStart는 어떨까요?! zeroPadding이 어느 부분에 필요한지도 적어주는게 좋을 것 같아요! 😊

2022-08-14 05:49 UTC, kkojae91 commented on frontend/src/components/ReminderModal/index.tsx
> +
말씀해주신 방향으로 수정하게 된다면 `BUTTON_TEXT.생성` 과 같이 한글이 들어가게 되는데 어색해보이진 않으신가요??

타입을 위한 프로퍼티명 변경을 하는 것 같아 어색해보이는 것 같아요!
제가 한글 변수명을 사용하는게 익숙하지 않아서 그러는 것 같기두 하구요!
create, modify, cancel 이라는 쉬운 단어들이 있는데 한글 프로퍼티를 선택하는 기준이 있을까요?!

2022-08-14 05:53 UTC, kkojae91 commented on frontend/src/components/ReminderModalOptions/style.ts
> +  left: -9999999999999999px;
display none을 추가해줘도 되는 부분인 것 같네요! 👍🏼
혹시 혹시 모르니까 -99999999px 또한 추가하는 것에 대해서는 어떻게 생각하시나요?!

```css
display: none;
top: -9999999999px;
left: -9999999999px;
```

2022-08-14 05:55 UTC, kkojae91 commented on frontend/src/components/ReminderModalToggleDropdown/index.tsx
> +        <Styled.Text>{text}</Styled.Text>
Icon component를 children으로 받아주는 방법도 좋은 방법인 것 같아요! 적용하도록 하겠습니다.

2022-08-14 05:58 UTC, kkojae91 commented on frontend/src/components/ReminderModal/index.tsx
> +
해당하는 로직을 제거하게 되면,
dropdown component 클릭했을때, UI가 해당 날짜및 시간으로 업데이트가 되지 않는 문제가 존재해요!

조금 어색하다고 생각한 부분이긴 한데 더 좋은 아이디어가 있다면 남겨주세요~!

2022-08-14 06:17 UTC, kkojae91 commented on frontend/src/hooks/useReminderModal.ts
> +  const { year, month, date, hour, minute } = getDateInformation(new Date());
useSetReminder 좋은 것 같아요! 👍🏼

2022-08-14 06:21 UTC, kkojae91 commented on frontend/src/components/ReminderModalOptions/index.tsx
> +function ReminderModalOptions({
TimePicker 좋은 것 같아요! input이라고 하기에는 input tag만 존재하는게 아닌 label 테그로 감싸져 있는 형태이니 inputWrapper 정도는 어떨까 싶어요!

그리고 이 컴포넌트를 시간 관련 데이터만 사용하는게 아니고 날짜 관련 데이터도 사용하기 때문에 `DateTimePickerOptionInputWrapper` 혹은 `DateTimePickerInputWrapper`는 어떨까 싶어요!
호프 생각은 어떠시나요?

2022-08-14 06:22 UTC, kkojae91 commented on frontend/src/components/ReminderModalToggleDropdown/index.tsx
> +  IconComponent: () => JSX.Element;
해당하는 부부은 컴포넌트를 어떻게 사용하는가에 따라 다른 것 같아요!
`() => JSX.Element`로 사용한 이유는
사용처에서
`<IconComponent />` 와 같은 형태로 사용하기 위해서 타입 설정을 위와 같이 했던 것 이에요! 이 부분은 IconComponent를 children으로 받는 방식으로 진행하겠습니다!

2022-08-14 06:29 UTC, kkojae91 commented on frontend/src/components/ReminderModalOptions/index.tsx
> +            {isPadStart ? optionText.padStart(3, "0") : optionText}
여러군데에서 사용하는게 아니고, 단순 연산에 코드라인도 길지 않아 한눈에 잘 들어오는데 padStart 로직을 꼭 분리해야할 필요가 있을까요?! 😯

2022-08-14 06:30 UTC, kkojae91 commented on frontend/src/hooks/useReminderModal.ts
> +  );
위에서 설명 드렸어요!!

2022-08-14 06:31 UTC, kkojae91 commented on frontend/src/components/ReminderModalOptions/index.tsx
> +  handleChangeText: (event: ChangeEvent<HTMLInputElement>) => void;
좋은 타입을 제공해주고 있네요! 적용하도록 할게요~!😊

2022-08-14 06:32 UTC, kkojae91 commented on frontend/src/hooks/useReminderModal.ts
> +  const lastDate = new Date(year, month, 0).getDate();
이부분은 getDateInformation을 재활용 하면 해결될 수 있겠네요!👍🏼
체크해주셔서 감사해요!

2022-08-14 06:32 UTC, kkojae91 commented on frontend/src/components/ReminderModalToggleDropdown/index.tsx
> +  handleToggleDropdown,
위에서 말씀드린 것 처럼 DateTimePicker***로 변경하도록 할게요! 👍🏼

2022-08-14 06:58 UTC, moonheekim0118 commented on frontend/src/components/ReminderModalOptions/style.ts
> +  left: -9999999999999999px;
음... display:none 하면 뷰포트 상에서 아예 안보이는걸로 알고있는데 꼭 top,left 위치를  -99999999px 로 해주어야할까용???

2022-08-14 07:00 UTC, moonheekim0118 commented on frontend/src/components/ReminderModal/index.tsx
> +
맞아요 어색한것같아요 ㅎㅎ 이 부분 그러면 지금 대로 냅두고 나중에 타입스크립트 리팩터링할 때 같이 처리해보아요.
예시에서 key 값을 한글로 둔 이유는 객체의 value 값을 타입으로 만들기위해서는 새로운 유틸리티타입을 만들어줘야할것 같아서 가장 간단한 방법을 제시한것이었어요!! 
타스 리팩토링할 때 같이 처리해요!!

2022-08-14 07:00 UTC, moonheekim0118 commented on frontend/src/components/ReminderModal/index.tsx
> +
흠흠 그랬군요. 설명 감사드립니다!! 이 부분 저도 더 고민해볼게요 !

2022-08-14 07:01 UTC, moonheekim0118 commented on frontend/src/components/ReminderModalOptions/index.tsx
> +function ReminderModalOptions({
Wrapper 는 뭔가 스타일링만을 위한 컴포넌트 같아서 어색한 것 같아요!
아예 input 역할만 하는게 아니라서 input 이라고 말하게 어색하다면 그냥 `DateTimePicekrOption` 이 더 괜찮을 것 같아요!

2022-08-14 07:02 UTC, moonheekim0118 commented on frontend/src/components/ReminderModalOptions/index.tsx
> +            {isPadStart ? optionText.padStart(3, "0") : optionText}
나중에 기획상 padStart 관련 정책이 바뀌면 그 때 해당 컴포넌트에 찾아와서 로직을 바꿔주는게 개발자에게 굉장히 번거로운 작업일거라고 예상했어요~
저는 그래서 이런거 다 util 로 분리해주는걸 선호하는데 어떠신가요??

2022-08-14 07:03 UTC, moonheekim0118 commented on frontend/src/components/ReminderModalOptions/index.tsx
> +  isPadStart,
needZeroPaddingStart 너무 좋아요!

2022-08-14 07:10 UTC, kkojae91 commented on frontend/src/components/ReminderModalOptions/style.ts
> +  left: -9999999999999999px;
훔... 호프 말이 맞긴합니다..!
이 부분은 `display: none;`으로 수정 반영할게요!!

2022-08-14 07:12 UTC, kkojae91 commented on frontend/src/components/ReminderModalOptions/index.tsx
> +            {isPadStart ? optionText.padStart(3, "0") : optionText}
기준이 명확하다면 util로 분리해도 좋다고 생각합니다!
해당하는 부분도 util로 분리하도록 할게요! 👍🏼

2022-08-14 10:27 UTC, kkojae91 commented
> 그리고, 리뷰하다가 문득 든 생각인데 모달 안에서 snackBar 를 띄워줄 일이 생길 것 같은데..그러면 Portal 을 하나만 사용하는게 문제가 될 수도 있을 것 같아요.
> 그래서 제안드리는건데 snackBar 용 포탈만 따로 만드는거 어떠신가요?

<img width="745" alt="image" src="https://user-images.githubusercontent.com/68001045/184532720-3f951548-dd6e-4dcf-a20e-4613c72d38c0.png">

이 부분은 모달 창 뒤로 쌓임 맥락이 생기게 되서 큰 문제는 되지 않을 것 같아요. 확인 한 번 해주세요!

[f4974b2](https://github.com/woowacourse-teams/2022-pickpick/pull/409/commits/f4974b24e0d33d67923b5ea47751b29db6bf3eff)

2022-08-14 10:27 UTC, kkojae91 commented on frontend/src/hooks/useReminderModal.ts
> +      Number(checkedMinute) < minute
관련 커밋
[a060526](https://github.com/woowacourse-teams/2022-pickpick/pull/409/commits/a060526bc44cc71de2c2d7afec2d15e1c955d56e)

2022-08-14 10:28 UTC, kkojae91 commented on frontend/src/hooks/useReminderModal.ts
> +  }
관련 커밋
[8e5fcb5](https://github.com/woowacourse-teams/2022-pickpick/pull/409/commits/8e5fcb53f2d26da26c5518a00bd26a8582b41671)

2022-08-14 10:28 UTC, kkojae91 commented on frontend/src/hooks/useReminderModal.ts
> +
관련 커밋 [c17abb4](https://github.com/woowacourse-teams/2022-pickpick/pull/409/commits/c17abb4910e8e12aa10b1c780d9e1df04ccc89c4)

2022-08-14 10:28 UTC, kkojae91 commented on frontend/src/components/ReminderModalToggleDropdown/style.ts
> +  border: 1px solid #dcdcdc;
관련 커밋 [a1f9516](https://github.com/woowacourse-teams/2022-pickpick/pull/409/commits/a1f95168a248775cbc2d03b7b0b2e3788892a558)

2022-08-14 10:28 UTC, kkojae91 commented on frontend/src/components/ReminderModalOptions/style.ts
> +  left: -9999999999999999px;
관련 커밋 [58a0dfd](https://github.com/woowacourse-teams/2022-pickpick/pull/409/commits/58a0dfd120b5ce1bdcbdd2274121d5a344bbfb6d)

2022-08-14 10:29 UTC, kkojae91 commented on frontend/src/components/ReminderModalToggleDropdown/index.tsx
> +        <Styled.Text>{text}</Styled.Text>
관련 커밋 [205ebf4](https://github.com/woowacourse-teams/2022-pickpick/pull/409/commits/205ebf40597c90b0e9405f8c427e9f0f64aaf894)

2022-08-14 10:29 UTC, kkojae91 commented on frontend/src/hooks/useReminderModal.ts
> +  const lastDate = new Date(year, month, 0).getDate();
관련 커밋 [12774e2](https://github.com/woowacourse-teams/2022-pickpick/pull/409/commits/12774e2e53cd2c8aec602a03dd83fb35d3fce14b)

2022-08-14 10:29 UTC, kkojae91 commented on frontend/src/hooks/useReminderModal.ts
> +
관련 커밋 [374d8c4](https://github.com/woowacourse-teams/2022-pickpick/pull/409/commits/374d8c4f1028e26f15696f1ed3783e51ca89ff27)

2022-08-14 10:30 UTC, kkojae91 commented on frontend/src/components/ReminderModalOptions/index.tsx
> +  handleChangeText: (event: ChangeEvent<HTMLInputElement>) => void;
관련 커밋 [103ae6f](https://github.com/woowacourse-teams/2022-pickpick/pull/409/commits/103ae6f4d84959b5f3b7ece996b10c03b0df28b0)

2022-08-14 10:30 UTC, kkojae91 commented on frontend/src/components/ReminderModalOptions/index.tsx
> +  isPadStart,
관련 커밋 [09364b3](https://github.com/woowacourse-teams/2022-pickpick/pull/409/commits/09364b3d95704473445a8da9e972be1a1b4ff3fc)

2022-08-14 10:30 UTC, kkojae91 commented on frontend/src/components/ReminderModalOptions/index.tsx
> +function ReminderModalOptions({
관련 커밋 [89bea9c](https://github.com/woowacourse-teams/2022-pickpick/pull/409/commits/89bea9cd6bc95d4da3071d55a4fb0cf33d1894dc)

2022-08-14 10:31 UTC, kkojae91 commented on frontend/src/hooks/useReminderModal.ts
> +  const { year, month, date, hour, minute } = getDateInformation(new Date());
관련 커밋 [7c4b5c8](https://github.com/woowacourse-teams/2022-pickpick/pull/409/commits/7c4b5c8db0e1117a23ccc6721297d7c897562d07)

2022-08-14 10:31 UTC, kkojae91 commented on frontend/src/components/ReminderModalOptions/index.tsx
> +            {isPadStart ? optionText.padStart(3, "0") : optionText}
관련 커밋 
87911bd

2022-08-14 10:54 UTC, moonheekim0118 commented
쌓임맥락으로 해결될 문제라면 괜찮겠네요!! 짚어주셔서 감사합니다 ㅎㅎ
반영해주신거 다 확인했어요! 잘 반영해주셔서 감사하구, 너무 고생많으셨습니다 : D 👍

2022-08-14 10:54 UTC, merged