feat: 다크모드 구현
woowacourse-teams/2022-pickpick pull request #411
Opened 2022-08-13 18:30 UTC by moonheekim0118

## 요약

 다크모드 구현 

## 작업 내용
![ezgif-5-06963475a5](https://user-images.githubusercontent.com/61469664/184506176-7947bf45-ab5a-44c2-bbbf-0da2d98747a5.gif)

- 다크모드 구현을 위해서 컬라 팔레트에 임시 색상 추가
- ThemeToggler 컴포넌트 작성
- useTheme 훅 작성
- useWebStorage 훅 작성 (추후에도 웹스토리지 사용될 것 같아서 작성해놨습니다.)
- useTheme -> Theme Provider 에 적용 

<br><br>

## 참고 사항

### 다크모드에 사용한 Color 
일단 임시로 사용했습니다. 
```
제일 어두운 배경 #181818
기본 컨테이너 색깔 #404040
버튼 및 더 짙은 색깔 #282828
조금 옅은 색깔 #B3B3B3
텍스트는 그냥 white 로 통일 
```

### 의논한 후 수정해야 할 부분
- ThemeToggler의 위치를 대체 어디에 둬야할지 모르겠어서 지금은 그냥 냅뒀습니다.ㅠㅠ..

### 다크모드를 구현하면서 무조건 리팩터링 해야겠다고 다짐 한 부분
1. **현재 컬러팔레트 구조 및 Theme 객체 구조**
- Theme 객체를 수정하면서 대체 COLORS.WRAPPER 와 COLORS.CONTAINER 의 차이점을 모르겠었습니다 .저희가 사용하고있는데, 도무지 어디에 사용되는지 출처를 모르게 코드를 작성했던 것 같아요. 이 부분 의논해서 Theme 객체만 봐도 어디에 사용되는 컬러인지 알 수 있도록 수정 해야겠다고 필요성을 느꼈습니다.

2. **SVG Icon 컴포넌트 작성 필요성**
- 이전에 꼬재가 말씀주신대로, Icon 별로 컴포넌트를 따로 작성해야겠다고 느꼈습니다. 그 이유는 지금 Icon 에 color 를 fill 로 넘겨주고 있기 때문이에요. 그래서 테마 색상이 적용되지 않습니다.  

## 관련 이슈

- Close #396 
 

<br><br>

2022-08-13 18:35 UTC, moonheekim0118 commented on frontend/src/App.tsx
> +      </ThemeProvider>
ThemeProivder 와 GlobalStyle 도 결국 index.tsx 에서 App.tsx 로 옮길 수 밖에 없었습니다..
테마를 변경해줘야하기 때문에요. ㅎㅎ

2022-08-13 18:35 UTC, moonheekim0118 commented on frontend/src/components/SearchInput/style.ts
이걸 추가한 이유는, 이게 누락되어있어서 input 의 background color 만 white 로 지정이 되어있더라구요. 그래서 부모(container) 의 색상이 투영되도록 변경했습니다.

2022-08-13 18:35 UTC, moonheekim0118 commented on frontend/src/components/ThemeToggler/index.tsx
> +
CheckBox 로 구현했는데, 혹여 개발자의 실수로 input type 은 절대 props 로 받아오지 못하도록 Omit 처리 했습니다.

2022-08-13 18:35 UTC, moonheekim0118 commented on frontend/src/components/ThemeToggler/style.ts
> +    content: url('https://shivanarrthine.com/public/images/icons/moon.svg');
해/달 모양 아이콘 사용했는데요, 이 부분 다음번에 파일로 받아서 assets 에 넣어주겠습니다.

2022-08-13 18:35 UTC, moonheekim0118 commented on frontend/src/hooks/useTheme.ts
> +  }, []);
이거 MacOS 에서 사용자가 설정해놓은 기본 셋팅값 확인하는 로직입니다.
`window.matchMedia("(prefers-color-scheme: dark)").matches` 가 true 면 다크모드로 설정되어있는거라고 하네용

2022-08-13 18:35 UTC, moonheekim0118 commented on frontend/src/hooks/useWebStorage.ts
> +  return [get, set] as const;
당연히 useStorage 는 get/set 밖에 없을것이라고 판단되어서 배열로 내려주었어요. 
그리고 사용처에서 해당 메서드 이름도 변경되면 좋을 것같아서요.

2022-08-13 18:35 UTC, moonheekim0118 commented on frontend/src/index.tsx
> -}
작업하다가 그냥..msw 로직이 index.tsx 맨 최상단에 있는게 더러워보여서 분리해주었습니다.

2022-08-14 07:25 UTC, kkojae91 requested changes
혼자서 컬러값 선택하시고!
번거로운 작업하시느라 수고많으셨어요! 
코멘트로 몇가지 궁금한 사항을 작성했는데 확인해주시면 감사하겠습니다!
토글 위치는 나중에 오프라인에서 같이 고민해봐요! 👍🏼

2022-08-14 07:25 UTC, kkojae91 commented on frontend/src/hooks/useWebStorage.ts
> +  return [get, set] as const;
해당하는 부분은 개인적으로는 객체를... 선호하긴 해요!
다른 부분들도 객체로 사용하고 있으니 통일된다면 더 좋을 것 같아요!

그런 의미에서 get, set function은 화살표 함수가 아닌 일반 함수로 사용한 이유가 있을까요?! 😯

2022-08-14 07:25 UTC, kkojae91 commented on frontend/src/hooks/useTheme.ts
> +  }, []);
아직 해보지 않은 부분인데 호프 덕에 배워가네요!!
이 부분은 window에서도 대응해줘야 하는 부분은 아닌가요?! 😯

2022-08-14 07:25 UTC, kkojae91 commented on frontend/src/components/ThemeToggler/index.tsx
> +
예외 상황 처리해주시는 것 너무 좋아요! 👍🏼

2022-08-14 07:25 UTC, kkojae91 commented on frontend/src/components/SearchInput/style.ts
다크모드 구현하면서 놓쳤던 부분을 체크하게 되었네요!! 좋아요~!

2022-08-14 07:25 UTC, kkojae91 commented on frontend/src/@styles/theme.ts
> +} as const;
혼자서 하시기 많이 번거롭고 힘드셨을텐데 고생많으셨어요 호프!! 👍🏼👍🏼👍🏼👍🏼

2022-08-14 07:27 UTC, moonheekim0118 commented on frontend/src/hooks/useWebStorage.ts
> +  return [get, set] as const;
화살표함수로 하는거 깜빡했어요  지적해주셔서 감사합니당!!  😭 
리턴타입도 객체로 바꾸도록 할게요!

2022-08-14 07:29 UTC, moonheekim0118 commented on frontend/src/hooks/useTheme.ts
> +  }, []);
제가 잘못알았네요..허허..
MacOS 뿐만 아니라 윈도우에서도 같은 로직으로 다크모드 체크 할 수 있다구 합니다..!!! 
허위사실유포해서 죄송합니다 흑

https://usefulangle.com/post/318/javascript-check-dark-mode-activated#:~:text=Dark%20mode%20can%20be%20detected,or%20not%20let%20matched%20%3D%20window.

2022-08-14 08:41 UTC, moonheekim0118 commented on frontend/src/components/ThemeToggler/style.ts
> +    content: url('https://shivanarrthine.com/public/images/icons/moon.svg');
반영 완료했습니다 

[0977b36](https://github.com/woowacourse-teams/2022-pickpick/pull/411/commits/0977b36632798be553726ec89a113a6ef9cef822)

2022-08-14 14:14 UTC, merged