fix: 메시지 조회 시 해당 회원의 북마크일 경우만 isBookmarked: true 반환
woowacourse-teams/2022-pickpick pull request #413
Opened 2022-08-14 04:27 UTC by hyewoncc

## 요약

메시지 목록 조회 시 해당 회원의 북마크만 조회합니다  

<br>

## 작업 내용

기존에 해당 회원 조회 조건을 안걸어서, 누가 한 것이든 북마크가 존재만 한다면 `isBookmarked: true`로 나가고 있었습니다  
이를 해당 회원의 북마크만 조회하도록 수정했습니다  

<br>

## 관련 이슈

- Close #408 

<br>

2022-08-15 01:45 UTC, yeon-06 approved these changes
깔끔한 수정 👍👍👍

2022-08-15 23:53 UTC, JangBomi requested changes

2022-08-15 23:53 UTC, JangBomi commented on backend/src/main/java/com/pickpick/message/application/MessageService.java
> +
회원의 북마크만 조회하는지 확인하는 테스트룰 추가하면 어떨까요?

2022-08-16 00:30 UTC, HJ-Rich approved these changes

2022-08-16 00:32 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/application/MessageService.java
> +
코멘트 보고 바로 추가하려고 했는데, 현재 `MessageService` 테스트 코드 변경 PR을 올려 둔 상태라, 이 PR이 처리 된 후에 추가하는 게 나을 것 같아요!  
개인적으로는 북마크/리마인더 조회랑, 요청 케이스에 따른 메시지 정렬을 다른 클래스로 분리하는 게 낫겠다 싶은데, 오늘 백엔드끼리 얘기해봐요~

2022-08-16 00:34 UTC, JangBomi commented on backend/src/main/java/com/pickpick/message/application/MessageService.java
> +
그렇다면 Approve 로 수정하겠습니다!! MessageService 테스트코드 변경 PR 적용 후 해주세용 🙇‍♀️

2022-08-16 00:35 UTC, JangBomi approved these changes

2022-08-16 00:36 UTC, merged