feat: 메시지 조회 테스트 리팩토링
woowacourse-teams/2022-pickpick pull request #421
Opened 2022-08-15 08:39 UTC by hyewoncc

## 요약

메시지 조회 서비스 통합 테스트 리팩토링  

<br>

## 작업 내용

`MessageServiceTest`를 아래와 같은 목적으로 리팩토링 했습니다 
- `@Sql` 선언된 sql문 내부를 보지 않아도 되도록 (=픽스쳐를 자바 코드 상에서 볼 수 있도록) 합니다  
- `MessageRequest`를 생성할 때 팩토리 클래스의 메서드 이름을 통해 어떤 요청인지 읽기 쉽도록 합니다  

<br>

`ParameterizedTest`는 아래와 같은 이유로 해제했어요  
- 왜 테스트가 복잡해보일까? 를 생각했을 때 **여러 조건을 한 메서드에서 검증하려고 하기 때문** 이라고, 조언을 듣고 생각했습니다  
- 그래서 조건을 광범위 -> 작은범위 로 흘러가도록 쪼개서 테스트하면 어떨까? 했어요  
  - 예를 들면, 20개를 조회했을 때 20개가 나온다
  - 더 조회할 게 없으면 `isLast`가 `true`다  
  - 파라미터가 없으면~ 
  - 특정 파라미터가 있으면~  
 
보기에 따라서 개악으로 느껴질 수도 있을 것 같아서 테스트에 대해 얘기 더 나눠봐도 좋을 것 같아요   
또, 앞선 PR 커밋을 같이 올려놔서 의논/approve와 별개로 머지는 제가 할게요!  

<br>

2022-08-16 16:51 UTC, HJ-Rich approved these changes
고생 많으셨습니다.
회의 때도 많이 나눴지만 개인적인 의견은 코멘트로 다시 정리해봤습니다.

더 읽기 쉬운 테스트 코드는 어떤 형태인가
더 유지보수 하기 쉬운 테스트 코드는 어떤 형태인가
둘이 상충된다면 어디에 더 가치를 둘 것인가 등
여러 가지 고민을 할 수 있는 좋은 기회였던 것 같습니다.

고생 많으셨습니다.
어푸하겠습니다.

2022-08-16 16:51 UTC, HJ-Rich commented on backend/src/main/java/com/pickpick/message/domain/MessageRepository.java
> +    List<Message> saveAll(Iterable<Message> messages);
테스트에서만 사용되는 메서드인 것 같아요

2022-08-16 16:51 UTC, HJ-Rich commented on backend/src/test/java/com/pickpick/fixture/MessageFixtures.java
> +        return new Message(UUID.randomUUID().toString(), this.text, member, channel, this.dateTime, this.dateTime);
`UUID.randomUUID().toString()` 이 방법은 정말 좋은 것 같아요

2022-08-16 16:51 UTC, HJ-Rich commented on backend/src/test/java/com/pickpick/message/application/MessageServiceQueryTest.java
> +    @DisplayName("쿼리 파라미터와 count가 없다면, 회원의 첫번째 순서 구독 채널의 최신 메시지를 20개 내림차순 조회한다")
```suggestion
    @DisplayName("count만 전달됐다면, 회원의 첫번째 순서 구독 채널의 최신 메시지 20개를 작성시간 내림차순 조회한다")
```

내림차순의 기준이 명시되어 있지 않아 제안해봅니다!

2022-08-16 16:51 UTC, HJ-Rich commented on backend/src/test/java/com/pickpick/message/application/MessageServiceQueryTest.java
> +        MessageRequest request = emptyQueryParams();
물론 지속적으로 노력해볼 순 있겠지만,
한편으론 인정을 해야할 것 같기도 해요.
실제로 복잡한 로직이기 때문에, 복잡하지 않을 순 없는 것 같아요.
아무래도 이번 스프린트에서는 회의 때 이야기한 트레이드 오프에서 결정을 해야한다는 생각입니다.
그래서 저도 어느 방향으로 진행이 되도 괜찮은데 개인적인 의견은 남겨봅니다.

개인적으론 개별 케이스마다 given이 정말 많아졌다는 점에서
PR로 제시해주신 방법의 단점이 더 크지 않나 생각됩니다.

ParameterizedTest를 사용할 경우,
하나의 케이스에 대해 이해하고 나면 
그 다음 케이스들에 대해서는 쉽게 파악이 가능하다고 생각해요.
모든 경우의 수를 한 곳에서 테스트하기 때문에
추후 테스트 케이스가 늘어나거나 수정해야하는 경우에도
오히려 한 곳에만 집중하면 되니 더 수월한 점이 있다고 생각해요.

한 곳에서 몰아서 테스트할 경우,
봄이 제시해준 의견처럼 리팩터링 하기 어렵다고 느껴지는 점도 공감이 가는 지점이 있지만,
이처럼 로직들이 분산되게 되면, 이들이 결국 관리가 어려워질 거라는 생각이에요.
규모가 커질수록 어디에서 어디까지 테스트를 하고 있는지 파악하기 어려워질 것 같다는 생각이에요.
어찌보면 하나의 로직을 테스트하는 것인데, 응집도가 떨어지게 되는 것 같아요.

회의 때 했던 이야기의 반복이긴 하지만,
저는 서비스 레이어의 테스트가 가장 엄격해야 한다고 생각해요.

그런 관점에서 같은 데이터를 쌓아두고
여러가지 요청을 보냈을 때 어떻게 결과가 나오는지 보는 게 중요하다고 생각해요.
하나의 로직을 테스트하는 건데 
지금은 개별 케이스마다 데이터를 다르게 세팅하는 모습이라서 
개인적인 취향상 덜 엄격해서 아쉽다는 생각이에요.
보다 실제와 유사한 환경에서 테스트를 하고 검증하고 싶다는 생각입니다.

2022-08-16 16:51 UTC, HJ-Rich commented on backend/src/test/java/com/pickpick/message/application/MessageServiceQueryTest.java
> +        boolean isContainingKeyword = foundMessages.stream()
`isContainingKeyword` 를 `containsKeyword` 로 표현하면 어떨까요?
Collections 클래스에도 boolean을 반환하는 containsAll이 있어서 제안해봅니다

2022-08-16 16:51 UTC, HJ-Rich commented on backend/src/test/java/com/pickpick/message/application/MessageServiceQueryTestSql.java
> +    }
이 정도 깔끔하면 좋긴 하겠지만..
이런 형태를 보고나면 완전히 중복되는 코드여서 ParameterizedTest로 빼고 싶어지는...
반복이군요 ㅋㅋㅋ

2022-08-16 16:51 UTC, HJ-Rich commented on backend/src/test/java/com/pickpick/message/application/MessageServiceTest.java
> -                        false),
테스트하려는 내용, 매개변수, 응답값이 모두 한 눈에 파악된다는 점에서 
저는 ParameterizedTest가 좋아보입니다.
물론 지적해주신 이 방식의 단점도 충분이 공감이 갑니다.

그러나 보다 실제와 유사한 테스트 환경, 엄격한 테스트,
하나의 로직에 대한 테스트를 한 곳에서 응집도 있게 관리한다는 점에서 매력을 느끼는 것 같습니다.

2022-08-17 04:58 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/message/domain/MessageRepository.java
> +    List<Message> saveAll(Iterable<Message> messages);
저도 테스트에서만 사용하는 메서드는 없으면 좋을 것 같아요~
for문 통해서 save를 하던가 하는 식이 될 것 같은데...
성능 개선을 위해 saveAll을 사용하고 싶다면 제가 말씀드렸던 SupportRepository를 만드는건 어떨까 다른 방법도 있을까 고민되네요 🤔

2022-08-17 06:07 UTC, yeon-06 requested changes
안녕하세요 써머 ㅎㅎ
리팩토링 정말정말정말 고생 많으셨습니다!!
몇 가지 남긴 질문에 대해 답변을 확인하고 싶어서 approve 대신 request changes로 해둘게요!❤

2022-08-17 06:07 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/message/application/MessageServiceQueryTest.java
> +    @DisplayName("쿼리 파라미터와 count가 없다면, 회원의 첫번째 순서 구독 채널의 최신 메시지를 20개 내림차순 조회한다")
count는 쿼리 파라미터와는 다르다고 생각하신걸까요 ?-?
저는 count도 쿼리 파라미터도 포함된다고 생각했는데 별도로 명시하셨기에 궁금해서 여쭤봅니다!

2022-08-17 10:06 UTC, JangBomi approved these changes
MessageServiceQueryTest 와 MessageServiceQueryTestSql, 그리고 이전의 방식인 ParameterizedTest 세 가지를 비교해봤을 때 저는 MessageServiceQueryTest 방식이 가장 좋은 것 같아요.
연로그와 리차드가 제가 생각한 리뷰들 다 남겨줘서, 저는 우선 Approve 할게요!
연로그가 추가로 써준 테스트케이스도 추가되면 좋을 것 같아요!!

2022-08-17 21:27 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/domain/MessageRepository.java
> +    List<Message> saveAll(Iterable<Message> messages);
삭제했습니다~

2022-08-17 21:29 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/message/application/MessageServiceQueryTest.java
> +    @DisplayName("쿼리 파라미터와 count가 없다면, 회원의 첫번째 순서 구독 채널의 최신 메시지를 20개 내림차순 조회한다")
😅 동일한 쿼리 파람인데 나머지는 필터링/검색의 조건, count는 별도로 자를 개수... 라는 생각이 깔려있어서 이렇게 적은 것 같네요  
수정했어요~

2022-08-17 21:33 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/domain/MessageRepository.java
> +    List<Message> saveAll(Iterable<Message> messages);
for문으로 save하도록 변경하고 삭제했습니다~

2022-08-17 21:34 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/message/application/MessageServiceQueryTest.java
> +class MessageServiceQueryTest {
보면서 비교하기 편하라고 임시로 분리해뒀습니다 ㅎㅎ `MessageServiceTest`로 올릴게요

2022-08-20 05:19 UTC, HJ-Rich commented on backend/src/test/java/com/pickpick/fixture/MessageFixtures.java
> +        return new Message(UUID.randomUUID().toString(), this.text, member, channel, this.dateTime, this.dateTime);
@JangBomi 봄 최고..😀

2022-08-20 05:23 UTC, HJ-Rich commented on backend/src/test/java/com/pickpick/message/application/MessageServiceQueryTest.java
> +        MessageRequest request = emptyQueryParams();
하나씩 하는 것도 좋은 방법이라고 생각해요
그런데 두 가지 전제가 필요하다고 개인적으로 생각합니다

- 하나의 로직에 대해 여러 테스트 케이스가 검증되어야할 경우 이 케이스들을 체계적으로 정리해야 합니다
  - 여러 클래스에 분산해서 관리한다는 의견도 나왔었기에 명시해봅니다!
- 각 케이스들은 최대한 실제 환경과 동일한 데이터를 기준으로 테스트해야 합니다
  - 저희의 경우 isLast 등의 이슈가 실제 존재했기에, 실제 사용환경과 최대한 비슷하게 꼼꼼히 검증해야 한다고 생각해요
- 가급적 여러 케이스들이 하나의 동일한 데이터 셋을 기준으로 검증되어야 한다고 생각합니다
  - 변인 통제 차원에서 필요성이 있다고생각합니다.
  - 같은 로직이고, 같은 데이터가 주어져있을 때, 요청에 따라 응답이 달라지는 부분에 대해 검증해야 하기 떄문입니다.

2022-08-20 05:24 UTC, HJ-Rich commented on backend/src/test/java/com/pickpick/message/application/MessageServiceQueryTest.java
> +        MessageRequest request = searchByKeywordInChannels(List.of(notice, freeChat), MESSAGE_KEYWORD, MESSAGE_COUNT);
저는 매직 넘버 등의 상수화가 중복 제거 보다는
의미있는 이름을 제공하는 데 더 의의가 있다고 생각해서
한 번만 사용되더라도 상수 처리를 선호합니다!

2022-09-02 04:06 UTC, hyewoncc commented
조회 테스트 개선을 쭉 고민했는데 오늘에서야 추가 커밋 올리네요 😅
`@Nested`를 이용해 아래 사항을 중점으로 개선해보았습니다 
 
1. 테스트 실행 시 출력 가독성 개선  
2. 테스트 픽스쳐 공유를 통한 리소스 절약  

한편 이렇게 바꿈으로써 생긴 고민도 있습니다 

1. 픽스쳐 공유를 위해 `@Nested`클래스 라이프 사이클을 변경  
2. 사용하지 않는 구독 변수 두 개의 할당이 불가피  

그래도 저는 현재 버전이 제일 마음에 드는 것 같아요  
괜찮다면 최종 머지할 때는 이 형태를 리마인더, 북마크 조회에도 적용해서 한 클래스로 합쳐 올리도록 하겠습니다!

2022-09-14 03:13 UTC, yeon-06 approved these changes
MessageServiceQueryTest의 내용을 MessageServiceTest로 옮겨주시기만 하면 될 것 같아요😄
정말정말정말 고생 많으셨습니다~~!!🥳🥳
수정 요청 사항이 있어서 merge는 안하고 approve만 할게요!

2022-09-14 03:13 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/message/application/MessageServiceQueryTest.java
> +            @DisplayName("해당 채널에 있고, 특정 단어가 포함된 메시지가 조회된다")
DisplayName을 합쳐보면 `특정 단어로 여러 채널에서 검색한다면 해당 채널에 있고, 특정 단어가 포함된 메시지가 조회된다` 라는 말이 완성되는데요
```suggestion
            @DisplayName("해당 채널들에서 특정 단어가 포함된 메시지가 조회된다")
```
위와 같은 변경은 어떨까 제안드려 봅니다👀

2022-09-14 03:15 UTC, yeon-06 approved these changes

2022-09-14 06:25 UTC, JangBomi approved these changes
써머 👍 👍 MessageServiceQueryTest.java 이름만 MessageServiceTest.java로 바꿔서 나가면 될 것 같아요!! approve는 하겠습니다 :)

2022-09-15 02:15 UTC, merged