feat: thread_broadcast 이벤트에 대한 기능 추가
woowacourse-teams/2022-pickpick pull request #424
Opened 2022-08-16 00:26 UTC by JangBomi

## 요약

thread_broadcast 이벤트에 대한 기능 추가
<br><br>

## 작업 내용

thread_broadcast 타입 이벤트에 대해서 처리를 할 수 있도록 추가했습니다.
thread_broadcast 이벤트는 두 가지 경우가 존재합니다.
자세한 케이스에 대해서는 이슈 #399 를 확인해주세요

<br><br>

## 참고 사항

제가 머지하겠습니다!
꼼꼼한 리뷰 부탁드려요 ❤️

<br><br>

## 관련 이슈

- Close #399

<br><br>

2022-08-16 06:49 UTC, yeon-06 requested changes
안녕하세요 봄😆
질문 사항이 많아서 답변 달아주신 후에 확인하기 위해 approve가 아닌 request changes를 하겠습니다!
인수테스트에 대해서는 `MessageEventAcceptanceTest`에 추가 동의합니다~

2022-08-16 06:49 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/SlackEvent.java
> +    public boolean isSameSubtype(String subtype) {
`final` 키워드 😆

2022-08-16 06:49 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageChangedService.java
> +        return SlackEvent.MESSAGE_THREAD_BROADCAST.isSameSubtype(subtype);
type은 다르고 subtype이 달라서 이런 문제가 발생하는군요...😂
봄 코드를 보니 isSameType도 static으로 생성하지 말고 이런식으로 slackEvent.isSameType()으로 호출하도록 변경하면 좋을 것 같다는 생각이 드네요 😄

2022-08-16 06:49 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +    private final MessageRepository messages;
개인 취향이지만 상수랑 생성자 주입받는 변수들 사이에 줄바꿈 하나 있으면 좋을 것 같아요 😄

2022-08-16 06:49 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +        SlackMessageDto slackMessageDto = convert(requestBody);
메서드 정렬이 필요할 것 같아요! 
처음에는 public -> private인가?했는데 조금 섞여있는 것 같네요😂
호출 순서를 참고하는건 어떨까요?

호출 순서
- (public) execute
  - (private) convert
  - (private) save
  - (private) createChannel
  - (private) toChannel
  
- (public) saveWhenSubtypeIsMessageChanged
  - (private) shouldSave
  - (private) save
  - (private) createChannel
  - (private) toChannel
- (public) isSameSlackEvent

2022-08-16 06:49 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +    public void saveWhenSubtypeIsMessageChanged(final SlackMessageDto slackMessageDto) {
이 친구도 슬랙 이벤트에 해당되는 친구일까요?
메시지 변경이 서브타입일때 메시지를 저장한다는게 어떤 의미인지 잘 모르겠어요ㅜ.ㅜ
메시지 변경과 메시지 저장은 다른 기능 아닌가요!?

2022-08-16 06:49 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +    public void saveWhenSubtypeIsMessageChanged(final SlackMessageDto slackMessageDto) {
상황 이해가 덜 되어서 이슈를 다시 꼼꼼히 살펴보고 왔는데요
아래 두가지 케이스가 오기 때문에 이렇게 처리하셨군요😂.........

- type=message, subtype=thread_broadcast
- type=message, subtype=message_changed, message.subtype=thread_broadcast

혹시 두가지 케이스가 어떤 경우에 오는지는 잘 모르겠는데 어떻게 다른가요??

2022-08-16 08:24 UTC, hyewoncc approved these changes
꼼꼼하게 봐 달라고 하셔서 봤는데 연로그가 이미 꼼꼼하게 봐주셨네요 ㅎㅎ  
꼭 고치면 좋겠다 싶은 부분은 없어서 approve 할게요~

2022-08-16 08:24 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +    public void saveWhenSubtypeIsMessageChanged(final SlackMessageDto slackMessageDto) {
- 스레드(댓글) 우클릭으로 채널에 전송  
- 채널에 전송했던 스레드(댓글)가 추후 수정 됐을 때 같아요!

2022-08-16 08:24 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +    public void saveWhenSubtypeIsMessageChanged(final SlackMessageDto slackMessageDto) {
참고링크!! 

https://github.com/woowacourse-teams/2022-pickpick/issues/399#issuecomment-1212753436

2022-08-16 08:24 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageChangedService.java
> +        }
슬랙에 참 이벤트가 다양하군요...😂
꼼꼼한 처리 고생하셨어요~

2022-08-16 08:24 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +    }
이 메서드를 사용하는 메서드의 이름이  `saveWhenSubtypeIsMessageChanged()`여서 `subtype`을 검증할 줄 알았어요  
`shouldSave`라는 이름에 이 데이터를 왜 저장해야하는지가 보이도록 포함시키는 건 어떨까요?  
저장 대상이 아닌 댓글에서 저장 대상인 메시지가 되는 거니까 `isNewMessage` 라던지..?    
🤔 저도 딱 이거다 싶은 이름이 생각나지 않아서 그냥 넘기셔도 괜찮습니다

2022-08-16 08:24 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +                .orElseGet(() -> createChannel(channelSlackId));
인라인 처리 별로일까요?

2022-08-16 08:24 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageChangedServiceTest.java
>              "db8a1f84-8acf-46ab-b93d-85177cee3e97",
반영을 위한 리뷰는 아닌데요!  
pk auto increment 문제를 막으려는 목적이시라면 이렇게 해도 동일하게 문제가 있을거에요  

```java
private Member testMember() {
  return new Member("U03MKN0UW", "사용자", "test.png");
}
``` 

이런 식으로 메서드로 분리하는 게 해당 목적에 더 맞을 것 같습니다 !!

2022-08-16 11:40 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +    public void saveWhenSubtypeIsMessageChanged(final SlackMessageDto slackMessageDto) {
써머가 말씀하신게 맞다면 후자의 경우에는 메시지의 값을 수정만 하면 되는거 아닌가요?
로직을 봤을 때는 save를 하고 있는 것 같아요 @.@!

2022-08-16 14:42 UTC, JangBomi commented on backend/src/main/java/com/pickpick/slackevent/application/SlackEvent.java
> +    public boolean isSameSubtype(String subtype) {
매의 눈 🦅👀

2022-08-16 14:55 UTC, JangBomi commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +        SlackMessageDto slackMessageDto = convert(requestBody);
createChannel과 toChannel은 후에 리팩토링을 통해서 제외할거라 가볍게 생각하고, 
save()의 위치가 고민되네요 ㅠㅠ 

execute -> convert -> save -> saveWhenSubtypeIsMessageChanged -> shouldSave -> (생략)

2022-08-16 15:05 UTC, JangBomi commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +    public void saveWhenSubtypeIsMessageChanged(final SlackMessageDto slackMessageDto) {
후자가 채널에 전송했던 스레드(댓글)가 추후 수정이 아니라, 스레드를 단 이후에 그 스레드를 채널로 전송한 경우였어요..!
따라서 스레드가 저장되어 있지 않아서, 채널에 전송한 경우 save()를 해줘야된다고 생각했어요!

이와는 별개로 써머가 말한 `채널에 전송했던 스레드(댓글)가 추후 수정 됐을 때`에 대한 처리를 생각을 못했네요ㅠㅅㅠ 이건 내일 확인해보고 추가하겠습니다!

2022-08-16 15:11 UTC, JangBomi commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +    }
shouldSave 보다 isNewMessage가 더 좋은 이름인 것 같아서 수정했어요!!

2022-08-16 15:25 UTC, JangBomi commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +                .orElseGet(() -> createChannel(channelSlackId));
```suggestion
        Member member = members.findBySlackId(slackMessageDto.getMemberSlackId())
                .orElseThrow(() -> new MemberNotFoundException(slackMessageDto.getMemberSlackId()));

        Channel channel = channels.findBySlackId(slackMessageDto.getChannelSlackId())
                .orElseGet(() -> createChannel(slackMessageDto.getChannelSlackId()));
```

인라인 처리하면 findBySlackId랑 exception 두 곳에서 모두 사용되어서 전 현재 상태가 좋다고 생각해요!
이건 연로그랑 리차드 의견도 들어보고싶습니다 :)

2022-08-16 15:34 UTC, JangBomi commented
남은 것
1. 메서드 순서 정리 [댓글](https://github.com/woowacourse-teams/2022-pickpick/pull/424#discussion_r946884385)
2. 채널에 전송했던 스레드(댓글)가 추후 수정 됐을 때 처리 [댓글](https://github.com/woowacourse-teams/2022-pickpick/pull/424#discussion_r946896179)
3. 인라인 처리 의견 들어보기 [댓글](https://github.com/woowacourse-teams/2022-pickpick/pull/424#discussion_r946925588)

2022-08-17 00:22 UTC, HJ-Rich commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +                .orElseGet(() -> createChannel(channelSlackId));
저는 인라인을 하지 않는 현재를 선호합니다~

2022-08-17 00:25 UTC, HJ-Rich commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageChangedServiceTest.java
>              "db8a1f84-8acf-46ab-b93d-85177cee3e97",
써머 굳굳~
상수 아닌 변수여도 매번 새로 생성하는 게 아니면
pk가 최초 1회 할당된후 계속 재사용돠는 게 맞는 것 같군요~!

2022-08-17 00:41 UTC, HJ-Rich approved these changes
고생 많으셨습니다
테스트 코드 스타일이 저랑 비슷해서 너무 읽기 쉬웠네요 ㅋ.ㅋ

저는 크리티컬한 이슈는 없어보이네요~
어푸하겠습니다~!

2022-08-17 00:41 UTC, HJ-Rich commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageChangedServiceTest.java
> +    }
저도 완전 똑같이 짰을 것 같아요 ㅋㅋ
굳~

2022-08-17 00:41 UTC, HJ-Rich commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastServiceTest.java
> +    @DisplayName("Thread_Broadcast 이벤트 시 채널이 저장되어 있으면 채널 신규 저장 없이 메시지를 저장한다")
'Thread Boradcast 이벤트 시'의 의미가 73번 라인의 DisplayName과 동일하다면 
73번 라인와 같은 표현을 써보면 어떨까 싶은데요
제가 정확히 이해한 게 맞을까요?

2022-08-17 00:41 UTC, HJ-Rich commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastServiceTest.java
> +    void saveMessageWhenMessageCreatedEventPassed() {
이 테스트 왜케 깔끔하게 잘 읽히나요~~ㅋㅋㅋ
굳

2022-08-17 00:41 UTC, HJ-Rich commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastServiceTest.java
> +        messageThreadBroadcastService.execute(MESSAGE_THREAD_BROADCAST_REQUEST);
변인 통제! ㅋㅋ 편안하고 멋있습니다!!

아래의 메시지 저장 여부를 분기하여 테스트하는 모습도 그렇습니다~!

머쪄!!

2022-08-17 00:44 UTC, HJ-Rich commented
이번 케이스의 서비스 내부 서비스 의존에 대하여 제 생각은 현재 구조 보다 더 나은 구조가 떠오르지 않는다 입니다!

조금 더 적극적으로 표현하자면 저는 지금도 충분히 좋은 것 같아요.
대안을 떠올려 본다면 SlackEvent에서 보다 세분하는 방향일텐데, 현재까지 경우를 봐서는 그곳에서 전체적인 복잡도를 높이기 보다는
연관 있는 서비스 구현체끼리 책임을 위임하는 현 설계가 좋아보입니다.

실제 이벤트가 그렇게 연관이 있는 상황이기에
코드를 읽는 입장에서도 이벤트 분류가 이런식으로 되는구나 하고 읽을 수 있을 것 같아요.

2022-08-17 04:36 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +        SlackMessageDto slackMessageDto = convert(requestBody);
저라면 후자를 선택할 것 같아요😄

2022-08-17 04:38 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +    public void saveWhenSubtypeIsMessageChanged(final SlackMessageDto slackMessageDto) {
이해했습니다!!
그렇다면 해당 기능이 MessageThreadBroadcastService의 역할인지 한번 생각해보면 좋을 것 같아요~
단순히 받아온 값을 저장만 한다면 MessageService는 아닐까? 라는 생각도 들고..
브로드캐스트 관련 값이라 파악하신거라면 지금이 맞을 것 같기도 하고.. 다른 분들의 생각도 궁금하네요 @.@

2022-08-17 04:38 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +                .orElseGet(() -> createChannel(channelSlackId));
저도 지금이 좋은 것 같아요~😄

2022-08-17 10:10 UTC, JangBomi commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastServiceTest.java
> +    @DisplayName("Thread_Broadcast 이벤트 시 채널이 저장되어 있으면 채널 신규 저장 없이 메시지를 저장한다")
넵!! 73번 라인과 같은 표현으로 수정하고, 하단의 test에 대해서도 수정했습니다!

2022-08-17 10:16 UTC, JangBomi commented on backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
> +    public void saveWhenSubtypeIsMessageChanged(final SlackMessageDto slackMessageDto) {
**ThreadBroadcast 관련 이벤트로 넘어오는 메시지를 저장**하는 역할이라 MessageThreadBroadcastService에 들어가야 한다고 생각했어요!
+ 단순히 저장하는게 아니라, thread_broadcast 이벤트인 경우에 이 메시지가 저장되어야하는가? 까지 판단하고 저장되어야하기 때문에 MessageThreadBroadcastService에 넣어야한다고 생각했습니다.

그리고 연로그의 의견 들어보고 생각해봤는데, 그렇다면 하단 save() 메서드 자체가 messageService에 속해있는건 어떨까? 하는 생각이 들었어요. 이 부분에 대해서는 좀 더 생각해보고 의견 공유할게요 :)

2022-08-17 10:52 UTC, yeon-06 approved these changes
😄👍👍 고생 많으셨습니다~~!!!

2022-08-17 10:55 UTC, merged