feat: 리마인더 요청 API 연결
woowacourse-teams/2022-pickpick pull request #439
Opened 2022-08-16 11:33 UTC by kkojae91

## 요약

리마인더 요청 API 연결(post, delete, put, get)

<br><br>

## 작업 내용

- reminders post API 생성 및 API_ENDPOINT 추가
- ISOConverter util 함수 return 값 수정
- MessageCard component props 수정
- ReminderModal component props 수정
- reminders API fetcher 추가 (getReminders, getReminder, putReminder, deleteReminder)
- useSetReminder custom hook mutate 로직 추가
- useSetReminder custom hook submit handler 추가 (modify, create, remove)
- Reminder page component 생성 (기존 Alarm page Component 제거)
- ReminderModal component에서 ReminderModalButtons component 분리

<br><br>

## 참고 사항

기존에 bookmark, reminder page에서 리마인더, 북마크 버튼이 모두 보이는 것도 bookmark page에서는 북마크 버튼만, reminder page에서는 리마인더 버튼만 보이도록 추가 수정했어요.

생각보다 까다로운 작업들이 있어서 조금 늦어진 감이 있네요!
리팩터링 해야하는 부분들이 많이 보입니다!
내일 같이 리팩터링 해요!! 👍🏼

아직 백엔드에 요청한 API 수정이 완료 되지 않아 내일 추가 작업 하면 최종적으로 구현은 완료 될 것 같아요

<br><br>

## 관련 이슈

- Close #415 

<br><br>

2022-08-16 17:06 UTC, moonheekim0118 requested changes
수고하셨습니다! 로직이 생각보다 많이 복잡했네요!
리마인더 모달이 어디에서 열리느냐에 따라서 UI 도, 후속처리도 다르니 고민 많이 하셨을 것 같아요.
지금은 props 로 내려주고, 해당 컴포넌트에서 props 값을 비교하여 분기처리해주고 있는 것 같은데

이 부분을 조금 더 개선해봅시다! 리마인더 모달의 사용처가 n 개일때마다 props 와 분기문을 n 개씩 늘려줄 순 없으니까요.
그리고 컨벤션 관해서 상의할 것도 있을 것 같습니다.

1. 훅에서 핸들러 함수, value 들을 객체로 묶어서 반환해주는 것
- 저는 사실 굳이..? 싶습니다 ㅠㅠ handlers.** 이렇게해서 한 depth 를 더 들어가야할 필요성을 느끼지 못해요. 어차피 저희 컨벤션 상, 모든 핸들러 함수의 prefix 가 handlers-* 니까요?
- 그리고 이 객체로 한겹 감쌀경우 타입핑하기도 매우 번거로워집니다..ㅠ  - ㅠ


2. 이벤트 핸들러 함수에 currying 을 쓸건지 `() => {} ` 을 쓸건지
- 저희 이거 혼동되고 있어요. 어디에선 커링 쓰고 어디에선 후자를 쓰네요! 정해줍시다.

3. 함수 마지막에 return 을 넣어야하는가?
- 저는 넣지 않는 편입니다... 어차피 함수의 끝까지 도달하면 void 가 알아서 반환되는걸로 알고있거든요. 이 부분도 상의해봅시다.

2022-08-16 17:19 UTC, moonheekim0118 commented on frontend/src/components/ReminderModal/index.tsx
> +function ReminderModal({
그리고 생각해보니 ReminderModal 네이밍도 그냥 Reminder 라고 해도 되지 않을까요?
굳이 Modal 은 외부에서 이 컴포넌트를 사용하는 방법이지, 이 컴포넌트의 역할 그 자체는 아니니까요!

2022-08-16 17:35 UTC, moonheekim0118 requested changes

2022-08-16 17:35 UTC, moonheekim0118 commented on frontend/src/hooks/useSetTargetMessage.ts
> +function useSetTargetMessage() {
이 네이밍도 사실 이게 리마인더를 위해서 타겟팅 된건지 뭘 위해서 타겟팅된건지 잘 모르겠어요~~~~ @.@

`useReminderTargetMessage`
`useRemindMessage`
이런 네이밍이 더 낫지 않을까요 !? 리마인더를 위해서 타겟팅 되었다는걸 명시해줍시다.

그리고 만약 State 로 가둔다면, 어차피 messageId 와 reminded 여부가 같이 바뀔 수 밖에 없으니, 객체로 해서 하나의 State 로 관리해주는 편이 더 간결할 것 같습니다.

2022-08-16 17:35 UTC, moonheekim0118 commented on frontend/src/hooks/useSetTargetMessage.ts
> +  };
하나로 묶어줍시다!!!!!!!!!

2022-08-16 17:35 UTC, moonheekim0118 commented on frontend/src/hooks/useSetTargetMessage.ts
> +
사실 두 값은 같이 변할 수 밖에 없으니 객체로 한꺼번에 관리해주는 편이 더 편리할 것 같아요.

2022-08-16 17:35 UTC, moonheekim0118 commented on frontend/src/hooks/useSetReminder.ts
> +
모달마다 해당 리마인더 데이터를 단건조회하는군요. 
하지만.......저희 서버에서 보내주는 메시지 객체에 RemindDate 를 담아주기로 했던 것 같은데.. 👀 .............하하핫

2022-08-16 23:34 UTC, kkojae91 commented on frontend/src/api/reminders.ts
> +    `${API_ENDPOINT.REMINDERS}?messageId=${messageId}`,
이후에 한 번에 리팩터링 진행하면 좋을 것 같아요

2022-08-16 23:35 UTC, kkojae91 commented on frontend/src/api/reminders.ts
> +};
제거해준다는 것을 깜박했네요! 👍🏼

2022-08-16 23:37 UTC, kkojae91 commented on frontend/src/components/MessageCard/index.tsx
> +        )}
좋네요 반영할게요~!

2022-08-16 23:57 UTC, kkojae91 commented on frontend/src/components/MessageCard/index.tsx
> +        )}
children으로 받아서 진행해도 될 것 같네요! 굿 👍🏼

2022-08-17 00:11 UTC, kkojae91 commented on frontend/src/hooks/useSetReminder.ts
> +
어제 API 수정을 요청한 것이다 보니 아직 반영이 안되어 있네요...! 하핫

2022-08-17 00:31 UTC, kkojae91 commented on frontend/src/components/ReminderModalButtons/index.tsx
> +function ReminderModalButtons({
children으로 받아서 진행해도 될 것 같네요! 굿 👍🏼

2022-08-17 00:33 UTC, kkojae91 commented on frontend/src/pages/Bookmark/index.tsx
> +                  isSetReminded={isSetReminded}
해당하는 부분은 제거해서 반영할게요~! 👍🏼

2022-08-17 00:38 UTC, kkojae91 commented on frontend/src/hooks/useSetTargetMessage.ts
> +function useSetTargetMessage() {
객체로 관리 할 지 분리해서 관리할 지 고민을 했었는데 객체로 관리해주는 방향이 조금 더 좋을 것 같네요! 👍🏼
수정 반영할게요~!

2022-08-17 08:03 UTC, merged