refactor: 슬랙 이벤트 중 멤버 관련 테스트 리팩토링
woowacourse-teams/2022-pickpick pull request #559
Opened 2022-09-30 07:08 UTC by hyewoncc

## 요약

슬랙 이벤트 중 멤버 관련 테스트를 리팩토링 했습니다  

<br>

## 작업 내용

아래 두 클래스의 테스트를 리팩토링 했습니다
- MemberJoinServiceTest
- MemberChangedServiceTest

일단 동의를 받고 고치고 싶은 부분이 있었는데요  
각 클래스에서 사용했던 `@ParameterizedTest`를 더 상세한 케이스로 분리했어요
결과가 같은 여러 주어진 케이스를 묶어둔 경우가 아니라, 
원인-결과가 묶여있어서, `MemberJoinServiceTest`의 경우 제가 연로그랑 같이 작성했음에도 다시 읽기 좀 헷갈리더라고요 

<img width="561" alt="스크린샷 2022-09-30 오후 12 05 34" src="https://user-images.githubusercontent.com/80666066/193210990-16f3cfeb-81ba-46de-aaf2-de568c30997f.png">

<img width="561" alt="스크린샷 2022-09-30 오후 12 06 34" src="https://user-images.githubusercontent.com/80666066/193211011-a12f982e-8486-4ee9-b7cd-c0edd77d632a.png">

이 경우에는 display name을 조금 불친절하게 적었던 것 같기도 하지만요 😅
`supports()` 테스트는 `isTrue() / isFalse()`로 나눴습니다  

<br>

## 관련 이슈

- #554 

<br>

2022-09-30 10:42 UTC, yeon-06 requested changes
슬랙 이벤트 - 멤버쪽도 빠르게 리팩터링 해주셨군요
정말 고생 많으셨습니다 써머😄👍
봄과 써머한테 의견을 여쭤본게 있는데 해당 답변을 확인하기 위해 일단은 request-changed로 해둘게요!
다시 요청 주시면 approve 드리겠습니다😃

2022-10-01 05:21 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/slackevent/application/member/MemberChangedServiceTest.java
> +        String displayName = "굿이에요굿굿굿";
굿이었는데 이름을 허가 안 받고 너무 막쓴 것 같아서 제 이름으로 바꿨습니다 하핫 😅

2022-10-01 05:25 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/slackevent/application/member/MemberJoinServiceTest.java
> +        Optional<Member> memberBeforeJoin = members.findBySlackId(slackId);
`slackId`가 DB에 유니크로 잡혀있어서 발생할 것 같아요! 
근데 오류를 검증하려고 짠 테스트는 아니라 이건 케이스를 추가해야 할 것 같네요  
저도 단건 저장의 경우 어떻게 검증을 해야할지 항상 고민입니다 🤧 
혼자 코드 짤 때는 조회 로직이 검증에 섞이는 게 싫어서 그냥 `저장 시 예외를 던지지 않는다`로 했었는데 이건 극단적인 예시 같고요
중간점을 찾는게 어려운 것 같아요 🤯 그냥 `findBySlackID/findById`로 했을 때 값이 나온다 만 검증하는 건 어떨까요

2022-10-01 05:29 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/slackevent/application/member/MemberChangedServiceTest.java
> +    @DisplayName("사용자 이름 변경 시 기본적으로 display_name 으로 변경")
훨씬 낫네요! 반영했습니다

2022-10-01 05:30 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/slackevent/application/member/MemberChangedServiceTest.java
> +                                      final String displayName, final String thumbnailUrl) {
아슬아슬하게 120자가 넘어서 자동정렬하면 `thumbnailUrl`만 내려오는데, 모양이 별로 안예뻐서 `displayName`도 같이 줄바꿈했어요  😁

2022-10-01 06:34 UTC, JangBomi requested changes
Approve 하기에는 애매해서(질문에 대한 답변 본 후에 Approve 하고싶어서요!) 우선 RC 합니다!

확실히 ParameterizedTest를 제거하고 Test로 나눈게 가독성 측면에서는 훨씬 좋은 것 같아요. 써머 최고입니다 👍

2022-10-01 06:34 UTC, JangBomi commented on backend/src/test/java/com/pickpick/fixture/MemberFactory.java
> +    }
이렇게 MemberFactory를 사용하면 기존 채널이나 메시지 서비스 테스트에서도 해당 MemberFactory의 멤버를 사용하여 테스트하는 것으로 변경되는걸까요? 

그리고 ChannelFixtures와 MessageFixtures와 다르게 Member는 함수로 Factory를 사용하신건지 이유가 궁금해요!!

2022-10-01 06:34 UTC, JangBomi commented on backend/src/test/java/com/pickpick/fixture/MemberFactory.java
> +}
꼬재와 써머의 SlackId가 중복인데, 혹시 의도하신건가요?

아직 MemberChangedServiceTest와 MemberJoinServiceTest의 코드를 확인하기 전인데, MemberFactory에 SlackId가 중복인 멤버가 존재하는게 오잉? 이라는 생각이 들어서 리뷰 남겨요!!

2022-10-01 06:34 UTC, JangBomi commented on backend/src/test/java/com/pickpick/slackevent/application/member/MemberChangedServiceTest.java
> +        // given
위의 ParameterizedTest를 Test 2개로 분리하셨네요! 훨씬 각 테스트가 어떤걸 검증하는지 잘 보이는 것 같아서 좋아요 👍

2022-10-01 06:34 UTC, JangBomi commented on backend/src/test/java/com/pickpick/slackevent/application/member/MemberJoinServiceTest.java
> +    void supportsOtherEventFalse(final SlackEvent slackEvent) {
👍

2022-10-01 06:34 UTC, JangBomi commented on backend/src/test/java/com/pickpick/slackevent/application/member/MemberJoinServiceTest.java
> +        Optional<Member> memberBeforeJoin = members.findBySlackId(slackId);
음 우선 슬랙에서 보내주는 SlackId가 다른 사람인 경우에 중복일 경우는 없을 것 같다는 생각이 들고, 만약 중복된 경우라면 써머 말대로 DB에 unique로 잡혀있어서 오류가 발생할 것 같아요.

단건 저장의 검증은 정말 어렵네요 ㅠㅠ 저는 단건 저장 검증 테스트할 때는 이 테스트처럼 뭔가 고유값을 가진 사람이 없는 상태임을 검증하고 저장하면 사람이 생겼다!를 검증하는 편이긴 합니다..!

2022-10-01 08:14 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/fixture/MemberFactory.java
> +    }
채널도 원래 팩토리였는데 `enum`으로 바꿨습니다!
`enum`을 하면 `XXX.create()`로 써줘야 하는 게 불필요하게 코드가 늘어나는 것 같아서 팩토리를 선택했었는데요,
메시지의 경우는 전체 values를 사용해야 하는 경우가 있는 반면, 팩토리로 만들었던 채널, 멤버는 보통 한 개의 객체만 필요해서 팩토리로 했었어요
그런데 인수테스트의 경우 지금 메시지 서비스 테스트에서 `enum`의 `values`를 가져오는 것 처럼, 복수의 채널, 멤버가 필요한 경우가 있다고 연로그가 의견주셔서 채널도 `enum`으로 바꿨습니다!
멤버도 `enum`으로 바꿀 생각이에요!

2022-10-01 08:16 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/fixture/MemberFactory.java
> +}
😂 의도하지 않았습니다!! 복붙의 폐해 같네요, 수정할게요

2022-10-02 05:10 UTC, yeon-06 approved these changes
수정은 아직이신 것 같지만 의견을 여쭌 부분에 대해서는 답변을 들어서 approve할게요!
화이팅입니다😄👍

2022-10-03 09:27 UTC, JangBomi commented on backend/src/test/java/com/pickpick/fixture/MemberFactory.java
> +    }
좋아요!! 감사합니다 :)

2022-10-03 09:28 UTC, JangBomi approved these changes
저도 답변 들어서 approve 합니다!! 나중에 완료되면 머지부탁드려요 👍

2022-10-03 10:52 UTC, merged