feat: 북마크 정렬 기준 변경 및 서비스 테스트 리팩터링
woowacourse-teams/2022-pickpick pull request #568
Opened 2022-10-01 10:33 UTC by hyewoncc

## 요약

- 북마크 정렬 기준을 생성 시간으로 변경  
- 북마크 서비스 테스트 리택터링  

<br>

## 작업 내용

북마크 정렬 기준을 생성 시간으로 변경했습니다  
이에 따라서 도메인에 생성 시간을 나타내는 `createdDate`가 추가되었습니다  
시간은 [JPA Auditing](https://hudi.blog/spring-data-jpa-auditing-create-update-date/)을 이용해 생성 시점에 자동 지정되게 했습니다   

또, 정렬 기준 변경으로 인수테스트 쪽에 사소한 수정이 있었어요  
다른 얘기하고 싶은 부분은 코드에 코멘트 달아둘게요   

<br>

## 관련 이슈

- Close #509 

<br>

2022-10-01 10:34 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/PickpickApplication.java
> +@EnableJpaAuditing
https://hudi.blog/spring-data-jpa-auditing-create-update-date/

2022-10-01 10:36 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java
> +        assertThat(bookmarkResponses.hasPast()).isFalse();
노란 경고줄이 떠서 무심결에 고쳤어요😅 원래 연로그가 인수테스트 작업 하기로 하셨던 것 같은데, 작업 중이라 충돌난다면 되돌려놓겠습니다 !

2022-10-01 10:40 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
> +    class saveAndDelete {
북마크 조회를 메시지 조회처럼 `@Nested + Lifecycle.PER_CLASS`로 하려고 했는데요,  
북마크 생성, 삭제 쪽은 `@AfterEach`로 데이터 초기화가 필요해서, 조회와 같은 `@Nested`에 넣을 수 없었어요  
그래서 1. 테스트 클래스를 분리하거나 2. `@Nested` 클래스를 분리하거나 둘 중 하나였는데, 후자로 작업했습니다

2022-10-01 10:45 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
> +                        () -> assertThat(foundBookmarks).allMatch(bookmark -> bookmark.getId() < targetBookmark.getId())
원래 시간으로 비교해야 맞는데 `service` 레이에서 반환하는 `DTO` 값에 북마크 생성 시각이 없어요 🥲
그래서 `id`로 비교하도록 했습니다

2022-10-02 05:12 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java
> +        assertThat(bookmarkResponses.hasPast()).isFalse();
아직 작업하지 않아서 괜찮습니다 ㅎ.ㅎ!!

2022-10-02 05:42 UTC, yeon-06 approved these changes
안녕하세요 써머~! 
변수명/메서드명 변경 제안 외에는 수정할 것이 없다고 판단해 approve 바로 하겠습니다!
고생 많으셨습니다😄👍👍👍👍

2022-10-02 05:42 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/PickpickApplication.java
> +@EnableJpaAuditing
저희 프로젝트 첫 Auditing이네요 크👍

2022-10-02 05:42 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
> +            int beforeSave = findBookmarksSize(member);
변수명을 보면 save 전에 존재하는 어떤 값 같은데 어떤 값인지는 안나와있네요!
size라는 의미도 함께 갖고 있으면 좋을 것 같아요😄

2022-10-02 05:42 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
> +            List<BookmarkResponse> foundHopesBookmarks = bookmarkService.find(onlyCount(totalSize), hope.getId())
onlyCount가 뭐하는 메서드인가 찾으려고 했는데 RequestFactory에 있었군요!😀
`onlyCountRequest`라는 이름을 사용하거나 `~RequestFactory.onlyCount()` 방식으로 사용하는건 어떨까요?

2022-10-02 05:42 UTC, yeon-06 commented on backend/src/test/resources/bookmark.sql
> +values (1, 2, 1, '2022-07-12 14:21:33'),
엄청난 노가다... 정말 고생 많으셨습니다😭

2022-10-03 04:48 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
> +            int beforeSave = findBookmarksSize(member);
수정했습니다!

2022-10-03 04:51 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
> +            List<BookmarkResponse> foundHopesBookmarks = bookmarkService.find(onlyCount(totalSize), hope.getId())
`static import`를 제거해 `BookmarkRequestFactory.XXX()`으로 통일했습니다

2022-10-03 04:54 UTC, JangBomi requested changes
픽스처 관련해서 궁금한 것들 질문 남겨놓은거 답변 확인하려고 우선 RC 합니다!

써머 최고 ⛱️ 👍 ❤️

2022-10-03 04:54 UTC, JangBomi commented on backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
> +            Message message = messages.save(PLAIN_20220712_18_00_00.create(channel, member));
혹시 이 부분 Member나 Channel 픽스처 사용도 멤버 관련 리팩토링 PR, 채널 관련 리팩토링 PR이 머지되면 픽스처에 있는 값으로 사용하실 예정인가요? 메시지는 픽스처 사용하시고 멤버나 채널은 그대로 두셔서 궁금해서 여쭤봅니다!

2022-10-03 04:54 UTC, JangBomi commented on backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
> +        List<Message> savedMessages = createAndSaveMessages(notice, kkojae);
여기서는 픽스처 사용이 `호프` `꼬재` `공지사항` 등 실제랑 비슷한데 위는 사용자 다른사용자로 픽스처 구성하신 이유도 궁금합니다!

2022-10-03 04:54 UTC, JangBomi commented on backend/src/test/java/com/pickpick/fixture/BookmarkFindRequestFactory.java
> +    }
요청 파라미터에 개수 + 북마크 id가 모두 있는 경우는 없었나요?

이 부분은 제가 북마크 정렬기준이 헷갈려서 여쭤봐요ㅠㅠ

2022-10-03 07:32 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/fixture/BookmarkFindRequestFactory.java
> +    }
요 부분 최초의 테스트 코드는 제가 짰던 것 같아서 설명드리자면 개수는 몇 개를 가져올지 정할뿐 정렬 기준이나 다른 로직이랑 관여된게 없습니다😄
파라미터에 개수, 북마크 id 둘 다 보낼 수는 있는데요
실제로 실행하는 로직은 `onlyBookmarkId`랑 동일할거예요!

2022-10-03 08:09 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
> +            Message message = messages.save(PLAIN_20220712_18_00_00.create(channel, member));
네, 앞선 PR들 머지되면 픽스쳐로 변경할 예정입니다!

2022-10-03 08:09 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
> +        List<Message> savedMessages = createAndSaveMessages(notice, kkojae);
원래 다른 사용자값을 픽스쳐랑 비슷하게 맞춰두려다 어차피 바꿀 건데 의미없나..? 싶어서 안바꾸기 시작했어요 😂

2022-10-03 08:10 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/fixture/BookmarkFindRequestFactory.java
> +    }
원래 있었는데 테스트를 작성하다보니 사용하지 않게 되어서 제거했어요! 
연로그가 말씀하신 대로 내부 로직은 `onlyBookmarkId`랑 동일해서, 테스트 케이스를 추가할 필요성이 안느껴지더라고요

2022-10-03 09:23 UTC, JangBomi approved these changes

2022-10-03 09:26 UTC, JangBomi commented on backend/src/test/java/com/pickpick/fixture/BookmarkFindRequestFactory.java
> +    }
그럼 이 부분 `bookmarkId와 count를 모두 요청보내면 bookmarkId와 같은 로직이 실행된다`(??) 이런 느낌으로 테스트케이스 하나 추가하는거 어떨까요? 테스트코드가 문서화의 목적도 함께 한다고 생각했을 때는 추가하면 좋을 것 같아서 의견 내봐용!

2022-10-03 15:01 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/fixture/BookmarkFindRequestFactory.java
> +    }
테스트 코드 추가 후 머지하겠습니다 😁

2022-10-03 15:16 UTC, merged