test: 채널 관련 인수 테스트 개선
woowacourse-teams/2022-pickpick pull request #571
Opened 2022-10-02 13:31 UTC by yeon-06

## 요약

채널 관련 인수 테스트 개선

<br><br>

## 작업 내용

- 채널 인수 테스트 개선
- 채널 구독 인수 테스트 개선

<br><br>

## 관련 이슈

- Close #565

<br><br>

2022-10-03 06:10 UTC, hyewoncc requested changes
코드 풀 받아서 봤는데, 확실히 예전보다 개별 테스트 케이스에서 어떤 상황인지 흐름을 파악하기 좋아진 것 같아요! 🔥 
깔끔하게 변한 테스트 메서드 내부를 보니 `RestHandler` 도입을 잘했다는 생각이 드네요 ㅎㅎ 
확인해주셨으면 하는 코멘트들이 많아서 일단 `RC`로 남길게요!

2022-10-03 07:35 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java
> +        long notice_id = 1L;
static final로 선언된 상수이기 때문에 🐍 형태로 사용했어요!!ㅎㅎ

2022-10-03 07:36 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java
>      void subscribe() {
에고 이 부분이 누락되었네요 `가입_후_로그인()`으로 수정하겠습니다!

2022-10-03 07:42 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/fixture/ChannelFixture.java
> +    TEST_BE_4_NOTICE("C03NNNFNY01", "test-be-4기-공지"),
사용하지 않는 enum이라 아예 제거해버렸습니다 ㅎ.ㅎ

2022-10-03 12:31 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/support/SlackClientImpl.java
> +public class SlackClientImpl implements SlackClient {
여러분께 의견을 여쭙고 싶은게 있어요~!
SlackClient 구현체니까 SlackClientImpl이라는 이름을 썼는데 어떻게 생각하시나요?🤔

2022-10-03 15:23 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/support/SlackClientTest.java
> +public class SlackClientTest implements SlackClient {
요 친구도 `XXXTest` 형식이라 소나큐브가 테스트 클래스로 생각하는 것 같네요😅
이름 추천..받습니다...😂

2022-10-04 05:18 UTC, yeon-06 commented
오프라인에서 논의한대로 아래와 같이 이름 변경하겠습니다😄
- 인터페이스 SlackClient -> ApiCilent
- 실제 구현체 SlackClientIml -> SlackClient
- 테스트용 구현체 SlackClientTest -> FakeClient

2022-10-04 06:30 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/support/SlackClientImpl.java
> +public class SlackClientImpl implements SlackClient {
👍 오프라인에서 논의 완료

2022-10-04 06:30 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/support/SlackClientTest.java
> +public class SlackClientTest implements SlackClient {
👍 오프라인에서 논의 완료

2022-10-04 07:32 UTC, JangBomi approved these changes
RestHandle 도입하니까 훨씬 깔끔한 것 같아요!!

테스트 개선하시느라 고생 많으셨어요 연로그 최고 👍

2022-10-04 07:32 UTC, JangBomi commented on backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java
> +                .collect(Collectors.toList());
```suggestion
    private List<Long> 구독한_채널_id_목록(final String token) {
        ExtractableResponse<Response> channelsResponse = 유저_전체_채널_목록_조회_요청(token);
        return channelsResponse.jsonPath()
                .getList("channels.", ChannelResponse.class)
                .stream()
                .filter(ChannelResponse::isSubscribed)
                .map(ChannelResponse::getId)
                .collect(Collectors.toList());
```

token을 파라미터로 받아와서 조회하는건 어떨까요? 물론 이 메서드를 사용하는 코드에서는 `구독한_채널_id_목록(token)` 보다는 `구독한_채널_id_목록()`이 깔끔하고, 현재 이 클래스에서 다른 토큰을 사용할 일이 없긴 하지만, 뭔가 토큰이 하나라고 가정하고 짠 테스트가 된 것 같아서 의견 내봅니다!

2022-10-04 07:32 UTC, JangBomi commented on backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java
> +        long channelId = 1L;
여기도 밑 테스트처럼 channelId 대신 noticeId를 사용하는건 어떨까용?

2022-10-04 08:49 UTC, hyewoncc approved these changes

2022-10-04 08:52 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/auth/application/AuthService.java
> +    public AuthService(final MemberRepository members, final ExternalClient slackClient,
다른 작업들이랑 충돌나는게 너무 많아서 인수 테스트 관련 마지막 PR때 반영할 예정입니다!

2022-10-04 10:26 UTC, merged