refactor: utils, constants 폴더 구조 개선 및 Reminder util 함수와 타입 리팩터링
woowacourse-teams/2022-pickpick pull request #594
Opened 2022-10-06 17:48 UTC by moonheekim0118

## 요약
 utils, constants 폴더 구조 개선 및 Reminder util 함수와 타입 리팩터링
그 외 누락되었던 훅스 리턴타입 명시

**리팩터링 내용이 굉장히 많고 files changes 도 많습니다 ㅠ ㅠ**
ISOConverter 의 경우 더 논의해보아야겠다고 생각해서 일부러 안건들였습니다..!
유틸 함수에 대부분 주석을 추가해주었습니다!

## 작업 내용

### Utils 폴더 구조 개선
- @utils/index.ts  (범용적인 유틸 함수)
- @utils/date.ts (날짜 관련 유틸 함수)
- @utils/api.ts (api 관련 유틸 함수)

### Constants 폴더 구조 개선
- @constants/index.ts  (범용적인 상수)
- @constants/date.ts (날짜 관련 상수)
- @constants/api.ts (api 관련 상수)

### types 파일 추가 및 유틸타입 추가
- @types/date.ts ( date 관련 타입이 이곳 저곳에서 많이 쓰여서 분리해주었습니다!)

```ts
type ValueOf<T> = T[keyof T];
```
이렇게 생긴 유틸타입을 만들었습니다.
객체의 value 들의 유니온타입을 만들기 위한 유틸타입입니다.

### Reminder 에서 Date 와 Time 관련 상태의 타입을 string -> number 로 수정
이전에 논의 했던 대로, 보여주는 곳, 즉 UI 에서만 원하는 형태로 파싱 되도록 수정하고, 가지고 있는 상태의 타입은 number 가 되도록 수정했습니다.
이를 위해서 useInput 커스텀 훅에 아래와 같이 Generic 인자를 추가해주어야 했습니다.
```ts

interface Props<T> {
  initialValue: T;
  validation?: (value: any) => boolean;
}

interface UseInputResult<T> {
  value: T;
  handleChangeValue: ChangeEventHandler<HTMLInputElement>;
  changeValue: (value: T) => void;
}

function useInput<T>({
  initialValue,
  validation,
}: Props<T>): UseInputResult<T> {
  // ... 생략 
}

export default useInput;
```

- 이렇게 하니 서버에 보낼 때 다시 한번 number 로 파싱되는 과정이 제거되었습니다.
- 생각보다 UI 에서 입맛대로 넘버를 파싱해주는건 어렵지 않았습니다..!

### Util 함수 네이밍 개선 및 invalid -> isValid 로 수정 
코드 볼 때 잘 안읽히길래, date 관련 util 함수의 네이밍들을 최대한 명시적으로 개선해보았습니다! 혹시 더 좋은 네이밍이 있다면 마구마구 제안해주세요!
일단 저는 네이밍을 어떤 식으로..했냐면

- `get-*` : 단순히 특정 값을 리턴 하는 경우 사용
- `parse-*` : 어떤 값을 매개변수로 받아서, 문자열로 파싱하는 경우 사용
- `isValid-*` : 값의 유효성 체크 

 invalid -> isValid 로 수정  한 것은..이전에는 `올바르지 않는가?` 를 체크했는데 그것보다 `올바른가?`를 체크하는게 더 읽기 수월할거라고 생각했습니다. 부정연산보다 긍정연산이 좋다고 하니까요!

## 관련 이슈

- Close #590 #589 

<br><br>

2022-10-09 10:31 UTC, kkojae91 requested changes
일단 정말 고생많으셨어요 호프!
디렉토리 구조 변경하다 보니 filechange가 굉장히 많아졌네요! 👍🏼👍🏼👍🏼

같이 고민해봐야하는 것 같기는 한데, 호프 생각도 한 번 남겨주시면 좋을 것 같아요!

constants의 index 파일이 뭔가 정리되지 않는 느낌이 아직 남아있는 것 같아요!
처음에 구분은 범용적인 상수로 하자고 했는데, 다시 확인하니 이것 저것 다 섞여있는 느낌이 드는 것 같아요!
음.... MESSAGE, ERROR_CODE, ERROR_MESSAGE_BY_CODE 라도 message라는 파일을 생성해 추가로 분리하는 건 어떨까요?! PATH_NAME도 분리해서 관리되는 건 어떨까요?! 

> invalid -> isValid 로 수정 한 것은..이전에는 올바르지 않는가? 를 체크했는데 그것보다 올바른가?를 체크하는게 더 읽기 수월할거라고 생각했습니다. 부정연산보다 긍정연산이 좋다고 하니까요!

아래 코드 라인에도 설명을 추가로 작성했지만, 부정 연산자를 사용하게 되면 코드를 읽을 때 두번 생각해야하는 부분은 저도 동의하는 부분이에요!

어떤 부분에서 사용하는지에 따라 달라지는 부분일 것 같은데요.

`if (!isValid) {} 와 같은 형태라면, 올바른가?가 아닌가?` 라고 개발자가 두 번 해석을 해야하는 반면, `if (isInvalid) {} 일 경우 올바르지 않는가?` 로만 읽을 수 있기 때문에 부정연산자와 함수 네이밍은 다른 이야기인 것 같아요!

한 번 더 체크하면 좋을 것 같은 부분은 코멘트로 남겨뒀어요 확인하고 답변해 주세요!

2022-10-09 10:31 UTC, kkojae91 commented on frontend/src/hooks/@query/useMutateReminder.ts
> +      !isValidReminderTime({
요 부분 함수 네이밍은 이전 네이밍이 더 좋을 것 같아요!

코멘트에도 호프 생각을 남겨주시긴 했는데, 
부정연산자를 사용하면 읽기 힘들다는 이야기는 저도 동의해요! 👍🏼

하지만, 부정 연산자와 긍정 함수 네이밍은 다른 부분이라고 생각합니다!
긍정 함수 네이밍을 사용함으로 부정연산자를 사용하고 있다고 생각이들어요!

지금 네이밍을 변경하고 부정연산자를 사용함으로서 `올바른가?가 아닐때`로 코드 라인이 변경되었는데, isInvalid를 사용하게 될 경우 `올바르지 않는가?`로 코드라인을 유지할 때 가독성 측면에서 더 좋다고 생각합니다.

2022-10-09 10:31 UTC, kkojae91 commented on frontend/src/hooks/@shared/useInput.ts
> +}: Props<T>): UseInputResult<T> {
제네릭으로 타입을 받아오니 조금 더 범용적인 useInput이 된 것 같아요 좋아요! 👍🏼

2022-10-10 08:16 UTC, moonheekim0118 commented on frontend/src/@constants/date.ts
> +export const MINUTES = [0, 10, 20, 30, 40, 50];
constnats/api 에 as const 가 누락된 부분 수정했습니다! 짚어주셔서 감사합니다!

상수로 쓰이는 배열 같은 경우는 `as const` 로 지정할 경우 타입이 `readonly` 로 인식되어서, `number[]` 와 같은 타입에 할당되지 못하는 문제점이 있었습니다  😅 그래서 as const 를 붙이지 않았는데요..!
생각해보니 해당 배열들이 사용되는 `DateTimePickerOptions` 에서는 배열을 바꾸지 못하게 하는게 맞는 것 같아요! 그래서 위의 배열들에 모두 as const 를 붙이고, `DateTimePickerOptions` 의 props 타입을 readonly 배열로 바꾸어주었습니다!

2022-10-10 09:16 UTC, moonheekim0118 commented on frontend/src/@utils/index.ts
> +  return value.toString().padStart(2, "0");
적용했습니다! 

[e332b80](https://github.com/woowacourse-teams/2022-pickpick/pull/594/commits/e332b801ae795f9e6a8bbf7b8266f246bbd1b9ee)

2022-10-10 09:57 UTC, moonheekim0118 commented on frontend/src/@utils/index.ts
> +  return typeof value === "string";
<img width="650" alt="스크린샷 2022-10-10 오후 6 54 41" src="https://user-images.githubusercontent.com/61469664/194840597-42a5905b-0754-4441-ba6a-f2bffd4e8c81.png">

이게..따로 함수시그니쳐로 사용하면 이런 문제가 있어요 😭 
무조건 boolean 으로 리턴타입을 명시하라구 해요...
이 부분 더 알아보겠습니다..!

2022-10-11 01:19 UTC, moonheekim0118 commented on frontend/src/hooks/@query/useMutateReminder.ts
> +      !isValidReminderTime({
좋은 지적과 의견 감사합니다!
저는 단순히 부정 함수 네이밍이라 읽기 불편하다고 생각해서 바꾸었는데, 꼬재 의견을 들어보니 이렇게 됨으로써 `Not 올바른가` 를 검사함으로써 조금 어색해진 것 같아요ㅎㅎ
그래서 원래대로 바꾸었습니다 ! 감사합니당  : D 
[90920a7](https://github.com/woowacourse-teams/2022-pickpick/pull/594/commits/90920a72ba8791485b5bffb0ed66d6a7b45646bc)

2022-10-11 12:00 UTC, moonheekim0118 commented
꼬재! 아프지마세요 ㅠ ㅠ
피드백 모두 반영했습니다! 
코드에 써주신 것 모두 꼬재의 의견에 동의해서 반영습니당 ㅎㅎ

- inValid 네이밍 유지 [90920a7](https://github.com/woowacourse-teams/2022-pickpick/pull/594/commits/90920a72ba8791485b5bffb0ed66d6a7b45646bc)

- constants/path , constants/message 생성하여 분리 [25ff79b](https://github.com/woowacourse-teams/2022-pickpick/pull/594/commits/25ff79b2b567122b4f651de97483a15b0aae0d28)

> ERROR_CODE 상수의 경우 api 쪽에 더 가깝다고 생각해서 api 파일에 분리해놨는데 괜찮을까요 ?ㅆ?

그 외에도..

- ts 에서 기본적으로 제공해주는 VoidFunction 타입 사용하여 중복되는 `()=>void` 타입 제거   [497652b](https://github.com/woowacourse-teams/2022-pickpick/pull/594/commits/497652b3d5c5457a5d568e3eed6abe1e0c8c76ae) 
- api 요청 함수 타입 정의 [0e598e2](https://github.com/woowacourse-teams/2022-pickpick/pull/594/commits/0e598e27fd1fa10fa8f3dd2a686df79b117de18b)

해주었습니다~~ 수정하사항 있으면 말해주세요! ㅠ 쾌차하세요 ㅠ

2022-10-12 02:31 UTC, yeon-06 approved these changes
🌺🎉✨⭐**LGTM**⭐✨🎉🌺

2022-10-12 02:32 UTC, merged