feat: 채널 목록 조회 API 변경
woowacourse-teams/2022-pickpick pull request #596
Opened 2022-10-11 12:07 UTC by yeon-06

## 요약

채널 목록 조회 API 변경

<br><br>

## 작업 내용

### DB에 저장된 채널들
- `AS-IS`: 워크스페이스 내에 봇이 추가된 채널
- `TO-BE`: 워크스페이스 내에 존재하는 모든 public 채널

### 채널 목록 API에서 조회되는 채널
- `AS-IS`: DB에 존재하는 모든 채널 목록
- `TO-BE`: 특정 워크스페이스에서 내가 참가하고 있는 채널 목록

<br><br>

## 참고 사항

테스트는 일단 돌아만 가게 짜놨습니다!
피드백 주시면 반영하고 그냥 두시면 테스트 전체 리팩터링 때 다루게 될 것 같아요~

<br><br>

## 관련 이슈

- #588 

<br><br>

2022-10-12 08:01 UTC, hyewoncc requested changes
안녕하세요 연로그! 
워크스페이스 개인화로 로직에 생각보다 큰 변동이 있었군요 😵 고생많았어요!! 
예외 관련 코멘트는 확인해주셨으면 해서 `RC`로 남길게요!

2022-10-13 07:53 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/channel/application/ChannelService.java
> +    private final ExternalClient externalClient;
인터페이스의 이름을 따라가는게 좋을 것 같아서 `externalClient` 이름을 사용했습니다!
다른 곳에서 `slackClient`라고 표기된 것도 바꿔야할 것 같은데 해당 PR에서 바꿔도 적절할지에 대한 의문이 있어서 일단 보류해두었어요😂

2022-10-13 07:53 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/channel/application/ChannelService.java
> +        Map<String, Boolean> participation = findParticipation(member);
반영하겠습니다!

2022-10-13 07:54 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/channel/application/ChannelService.java
> +            throw new MemberNotFoundException(member.getId(), token);
`MemberTokenNotFoundException`으로 생성하겠습니다😄

2022-10-13 07:58 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/member/domain/Member.java
> +    public void markLoggedIn(final String token) {
어떤 이름이 `첫 로그인이라고 마킹한다`, `토큰이 저장된다`를 둘 다 해당되게 만들 수 있을까요?🤔
`fistLogin()` 같은 이름은 너무 두루뭉술할까요? ㅠㅠ

2022-10-13 07:58 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java
> +        String memberSlackId = MemberFixture.findFirst().getSlackId();
천재 써머.. 역시 몬스터 디벨로퍼👍

2022-10-13 13:21 UTC, JangBomi requested changes
연로그 안녕하세요! 꼭 반영해주셔야하는 리뷰 (익셉션 내부 필드 수정!)이 있어서 우선 RC 하겠습니다!

이외는 그냥 질문 또는 의견입니다 :)

변경점이 많았는데 꼼꼼하게 작성해주셔서 너무 좋았어요 👍

2022-10-13 13:21 UTC, JangBomi commented on backend/src/main/java/com/pickpick/support/SlackClient.java
>          OAuthV2AccessRequest request = generateOAuthRequest(code);
분리된거 최고 👍

2022-10-13 13:21 UTC, JangBomi commented on backend/src/main/java/com/pickpick/support/SlackClient.java
> +    public List<Channel> findChannelsByWorkspace(final Workspace workspace) {
메서드명 변경 후가 훨씬 좋아요!!

2022-10-13 13:21 UTC, JangBomi commented on backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
> +        member.markLoggedIn("xoxp-token");
`new Member("U00001", "연로그", "https://yeonLog.png", workspace)` 이 부분 MemberFixture 사용 안하신 이유가 workspace 때문인거겠죠? 😂

2022-10-13 13:21 UTC, JangBomi commented on backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
> +        }
```suggestion
        List<Conversation> conversations = Arrays.stream(channels)
                .map(channel -> Conversation.builder()
                        .id(channel.getSlackId())
                        .isMember(true).build())
                .collect(Collectors.toList());
```
빌더와 스트림 사용 어떨까요? 자동 setter라서 그런지 setIsMember가 아니라 setMember라서 처음 딱 보고는 `왜 true지?` 라고 생각이 들었어서 제안해봅니다!

2022-10-13 13:23 UTC, JangBomi commented on backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
> +        member.markLoggedIn("xoxp-token");
```
참고 사항

테스트는 일단 돌아만 가게 짜놨습니다!
피드백 주시면 반영하고 그냥 두시면 테스트 전체 리팩터링 때 다루게 될 것 같아요~
``` 이걸 나중에 봤네요 ㅠㅠ

2022-10-13 13:23 UTC, JangBomi commented on backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
> +        }
```
참고 사항

테스트는 일단 돌아만 가게 짜놨습니다!
피드백 주시면 반영하고 그냥 두시면 테스트 전체 리팩터링 때 다루게 될 것 같아요~
``` 
이걸 나중에 봤네요 ㅠㅠ

2022-10-14 01:12 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/member/domain/Member.java
> +    public void markLoggedIn(final String token) {
저는 `firstLogin()` 찬성이에요!  포괄적인 편이 하나만 나타내는 것 보다 낫다고 생각합니다

2022-10-14 01:47 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/channel/application/ChannelService.java
> +                .filter(it -> participation.isParticipant(it.getSlackId()))
다른 곳에서 사용할 일은 없긴 하지만 필요한 값만 던져주는게 메서드의 재사용성을 높여준다고 생각했습니다😄
저는 객체지향이  객체에게 상태를 꺼내서 수정하는게 아니라 상태를 알아서 변경하도록 명령하게 만들라고 생각했는데요
혹시 객체에게 객체를 던져준다는 말에 대해서 더 설명을 들을 수 있을까요?👀

2022-10-14 01:58 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
> +        member.markLoggedIn("xoxp-token");
fixture 사용하도록 수정했습니다 ㅎ.ㅎ

2022-10-14 02:29 UTC, JangBomi commented on backend/src/main/java/com/pickpick/channel/application/ChannelService.java
> +                .filter(it -> participation.isParticipant(it.getSlackId()))
메서드에게 객체를 넘겨주는 것이 `객체와 객체가 상호작용한다` 는 객체지향의 개념(????)을 지키는 것이 아닐까? 해서 남긴 리뷰였어요!

수정했을 때 `.filter(Participation::isParticipant)` 로 메서드 레퍼런스로 코드를 작성할 수 있다는게 가독성 측면에서 더 좋아보이기도 했고요!!

사실 엄청나게 확고한 근거와 논리가 있는게 아니라(🥲) 반영해주세요!! 하고 단게 코멘트를 어떻게 달아야할지 모르겠네용 흑흑 ,,,
리뷰는 Approve 하겠습니다!!

2022-10-14 03:47 UTC, hyewoncc approved these changes
리뷰 반영한 것 확인했어요 💯 수고하셨습니다!!

2022-10-14 03:54 UTC, merged