feat: 채널 생성 API 구현
woowacourse-teams/2022-pickpick pull request #597
Opened 2022-10-11 12:59 UTC by yeon-06

## 요약

채널 생성 API 구현

<br><br>

## 작업 내용

- [x] 채널이 생성되는 경우 해당 정보를 DB에 저장하는 API 구현
- [x] 서비스 테스트 작성
- [ ] 인수 테스트 작성

<br><br>

## 참고 사항

인수 테스트 쪽에서 채널 관련 테스트가 완전히 누락된 현상을 발견하였습니다
해당 테스트를 전부 추가하고 Draft를 해제하겠습니다😄

💥줍줍 앱의 Subscribe to bot events에 `Subscribe to bot events` 추가💥

<br><br>

## 관련 이슈

- #588 

<br><br>

2022-10-12 14:29 UTC, hyewoncc requested changes
연로그! 고생 많았어요
리뷰는 스타일 위주로 남긴 것 같은데요, 
앞선 #596 PR이랑 중복되는 부분이 많아서 나중에 이 PR만의 변경점을 따로 다시 확인하고 싶어서 일단 `RC`로 달아둘게요!

2022-10-12 14:29 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelRequest.java
> +
이번 PR의 변경점도 아니고, 그냥 궁금한 사안인데요! `ChannelRenameDto` 대신 `SlackChannelRenameDto`라고 이름붙인 이유가 있을까요?

2022-10-12 14:29 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/acceptance/slackevent/ChannelEventAcceptanceTest.java
> +    void 채널_생성_확인() {
다른 인수테스트 메서드 이름을 보니 좀 더 서술적으로 적는게 통일감 있을 것 같아요!
`새로운_채널이_생성되면_저장한다, 채널_이름이_변경되면_반영한다` 이런 식으로요

2022-10-12 14:29 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
> +    @Transactional
`@Transactional`이 붙은 이유가 있을까요?

2022-10-13 12:52 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelRequest.java
> +
`SlackChannelDto`로 변경되어야하는데 깜빡했네요😂
기존에 `ChannelDto`가 이미 존재하기 때문에 `SlackChannelDto`라는 이름을 붙여줬습니다~!

2022-10-13 12:59 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelRequest.java
> +
지금은 이름을 변경했는데 예전에 중복되는 클래스명이 존재했던걸로 기억해요~!
`ChannelRenameDto`로 변경하겠습니다!😄

2022-10-13 13:03 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/acceptance/slackevent/ChannelEventAcceptanceTest.java
> +    void 채널_생성_확인() {
인수 테스트 메서드명이 전체적으로 명사형으로 끝나는 것 같아서 `새로운_채널_생성_시_저장`, `기존_채널_이름_변경_시_반영`으로 바꿨습니다. ㅎ.ㅎ

2022-10-13 13:09 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
> +    @Transactional
아뇨 뭐좀 테스트해보다 지우는걸 깜빡했네요ㅠㅠㅠㅠ 삭제했습니다~

2022-10-13 13:33 UTC, JangBomi requested changes
연로그 안녕하세요!! 앞 PR이랑 겹치는 부분이 많은 것 같아서 저도 우선 RC 하겠습니다!

2022-10-13 13:33 UTC, JangBomi commented on backend/src/test/java/com/pickpick/fixture/WorkspaceFixture.java
> +    ;
워크스페이스 픽스처 만든거 앞 PR에도 될 예정인걸까욤??

2022-10-14 02:00 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/fixture/WorkspaceFixture.java
> +    ;
네~~😄
앞 PR이 머지되면 해당 PR에서 pull받아온 뒤 적용 예정입니다!

2022-10-14 05:22 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/exception/member/MemberNotFoundException.java
> +    }
`MemberTokenNotFoundException`으로 변경 완료

2022-10-14 05:35 UTC, JangBomi approved these changes
연로그 최고 👍

2022-10-14 05:35 UTC, JangBomi commented on backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
> +            conversation.setMember(true);
요부분 앞 PR에서 리뷰 남겼던 빌더랑 다른 부분일까용?

2022-10-14 05:35 UTC, JangBomi commented on backend/src/test/java/com/pickpick/fixture/ChannelFixture.java
> +    NEW_CHANNEL("C0000000004", "새로운 채널", false),
줄바꿈 일부로 추가해두신걸까요??

2022-10-14 05:35 UTC, JangBomi commented on backend/src/test/java/com/pickpick/support/FakeClient.java
> +    public Participation findChannelParticipation(final String userToken) {
이 메서드 이름 수정 정말 좋은 것 같아요! 👍

2022-10-14 07:18 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
> +            conversation.setMember(true);
😱 충돌 해결하면서 마음대로 반영해버렸네요...

2022-10-14 07:19 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/fixture/ChannelFixture.java
> +    NEW_CHANNEL("C0000000004", "새로운 채널", false),
네! 마지막 파라미터가 true/false인 채널을 구분하기 위함입니다!

2022-10-14 07:42 UTC, hyewoncc approved these changes
리뷰 반영된 것 확인했어요!
변경점이 많아서 까다로운 작업이었을텐데 고생많으셨어요
approve 할게요! 💯💯💯

2022-10-14 07:47 UTC, merged