워크스페이스 개인화 작업 이후 서비스 테스트 코드 내부에서 workspace 사용하도록 수정
woowacourse-teams/2022-pickpick pull request #614
Opened 2022-10-15 16:15 UTC by JangBomi

## 요약

워크스페이스 개인화 작업 이후 서비스테스트 코드 내부에서 workspace 사용하도록 수정

<br><br>

## 작업 내용

- [x] ServiceTest 코드 내부에서 workspace를 사용하도록 수정(Member와 Channel 생성 시에 workspace 추가하도록 수정)
- [x] SlackEventService 관련 테스트 내부에 있던 static fixture 제거
- [x] 테스트 코드 내부에 남아있던 findById().orElseThrow() 제거
- [x] saveMember() 와 MemberFixture.create() 이 부분 통일

<br><br>

## 참고 사항

우선 정말 단순한 작업들 진행했습니다. 
Member와 Channel 내부에서 workspace가 없는 생성자들 제거하려했는데, 서비스테스트에서는 해당 생성자를 사용하는 모든 부분을 제거했지만 인수테스트가 남아있어서 아직 생성자 제거까지는 못했습니다.

생각보다 PR 변경점이 커져서 1차로 PR 올립니다.
남은 작업들
- [ ] 인수테스트에서 워크스페이스 없는 생성자 사용하는 곳 수정
- [ ] 서비스테스트에서 slackClient mocking 제거

<br><br>

## 관련 이슈

- Close #613 
- Close #612 
- #606 이 PR은 아직 작업이 남아있어서 close 하지 않겠습니다!

<br><br>

2022-10-16 04:46 UTC, yeon-06 requested changes
안녕하세요 봄!!😘
테스트 개선 정말정말 고생 많으셨습니다😭
자잘자잘하게 단 코멘트가 많아서 RC로 해두겠습니다~!

2022-10-16 04:46 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/channel/application/ChannelSubscriptionServiceTest.java
> +@Import(TestConfig.class)
TestConfig를 제거하고 FakeClient에 `@Component`와 `@Primary`를 달아서 빈으로 등록해주는건 어떨까요?😄
기존에는 인수 테스트에만 빈을 등록하기 위해 생성했었는데요
서비스에서도 빈 등록을 해줘야한다면 이제 테스트용 Config 파일은 필요 없을 것 같아요!

2022-10-16 04:46 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/channel/application/ChannelSubscriptionServiceTest.java
> +        //1  given
오타가 들어가있네요!👀
```suggestion
        //  given
```

2022-10-16 04:46 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/channel/domain/ChannelSubscriptionTest.java
> +        Member member = new Member("slackId", "유저 이름", "Profile.png", workspace);
여기서는 픽스쳐를 사용하지 않으신 이유가 있으실까요?👀

2022-10-16 04:46 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/channel/domain/ChannelTest.java
> +        Channel channel = new Channel("slackId", "채널 이름", workspace);
픽스쳐 미사용 코멘트 동일

2022-10-16 04:46 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/fixture/MemberFixture.java
>      }
캬 역시 천재 봄의 리팩터링.....👍
로그인 한 멤버 생성 / 하지 않은 멤버 생성 메서드 분리하니까 확실히 더 깔끔해보이네요😄

다만 `hasNeverLoggedIn`은 로그인한 적 있는지 체크하는 메서드처럼 느껴져서 이름 형식은 통일하면 좋을 것 같아요 ㅎ.ㅎ
`createLoginMember`, `createNotLoginMember` 이런 식으로 `createXXX` 형식은 어떨까요??

2022-10-16 04:46 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/member/domain/MemberTest.java
> +        Member member = new Member("U12345", "사용자", "test.png", workspace);
픽스쳐 미사용 코멘트 동일

2022-10-16 04:46 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/member/domain/MemberTest.java
> +        Member member = new Member("U12345", "사용자", "test.png", workspace);
픽스쳐 미사용 코멘트 동일

2022-10-16 04:46 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelCreatedServiceTest.java
> +                                "type", SlackEvent.CHANNEL_CREATED.getType(),
꼼꼼한 리팩터링 👍

2022-10-16 04:46 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageChangedServiceTest.java
> +        return messages.save(message);
요기도 다른 부분처럼 한 줄로 통일해도 깔끔해보일 것 같아요😄
```java
Workspace jupjup = workspaces.save(JUPJUP.create());
```

2022-10-16 04:46 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageChangedServiceTest.java
> +    private Message saveMessage() {
이름은 saveMessage()인데 다양한 값들을 초기화하고 있는 것 같아요!
init()랑 saveMessage()를 분리하는건 어떨까요?

해당 테스트에서 Message 생성 외에 다른 일들은 관심사가 아니라서 이렇게 분리하셨다는 생각이 들긴 해요
다른 메서드들에서도 Workspace, Member, Channel을 하나씩 생성하고 있으니 `@BeforeEach` 같은걸로 초기화 작업을 분리하는건 어떨까요??

2022-10-16 04:46 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageCreatedServiceTest.java
> +        String messageCreatedRequest = createMessageCreatedRequest(notice, message, summer);
요 값은 when이 아니라 given인 것 같아요😄

2022-10-16 04:46 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageCreatedServiceTest.java
> +        String messageRepliedRequest = createMessageRepliedRequest(notice, message, summer);
요 값은 when이 아니라 given인 것 같아요😄

2022-10-16 04:46 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageDeletedServiceTest.java
> +    private Message saveMessage() {
`MessageSavedServiceTest`의 `saveMessage()` 메서드 코멘트와 동일

2022-10-16 04:46 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageFileShareServiceTest.java
>                  "text", text,
요 값도 message에서 꺼내올 수 있지 않을까요?👀

2022-10-16 04:46 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastServiceTest.java
> +        String request = createMessageThreadBroadcastRequest(notice, message, bom);
요 값은 when이 아니라 given인 것 같아요😄

2022-10-16 07:47 UTC, JangBomi commented on backend/src/test/java/com/pickpick/channel/application/ChannelSubscriptionServiceTest.java
> +@Import(TestConfig.class)
이 부분은 다음 PR에서 다른 곳 SlackClient 제거하면서 같이하려고 했습니다!!

2022-10-16 07:48 UTC, JangBomi commented on backend/src/test/java/com/pickpick/channel/application/ChannelSubscriptionServiceTest.java
> +        //1  given
매의 눈 👀 👍

2022-10-16 07:49 UTC, JangBomi commented on backend/src/test/java/com/pickpick/channel/domain/ChannelSubscriptionTest.java
> +        Member member = new Member("slackId", "유저 이름", "Profile.png", workspace);
도메인쪽 테스트라 픽스처를 사용하지 않았어요! 도메인쪽 테스트도 픽스처를 사용해주는게 좋을까요?

2022-10-16 08:14 UTC, JangBomi commented on backend/src/test/java/com/pickpick/fixture/MemberFixture.java
>      }
맞습니다 이 부분 메서드 이름을 엄청 고민하다가, 사용하는 부분에서 `members.save(KKOJAE.hasNeverLoggedIn(jupjup));` 로 사용돼서 일단은 이 이름으로 하고 의견 받으려고 했어요!!
create와 형식을 맞추면 좋을 것 같긴한데 `로그인을 한 번도 한 적 없는 멤버`와 `로그인을 했었던 멤버`로 이름을 구분하는데 마땅한 이름이 잘 안떠오더라고요 ㅠㅠ
create 뒤로 붙을 멋진 이름 있을까요 ㅠㅠ ?

2022-10-16 08:47 UTC, JangBomi commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageChangedServiceTest.java
> +    private Message saveMessage() {
이 부분 기존에 saveMessage()로 메서드 분리가 되어있었어서 메서드 내부에서 리팩토링 진행했었는데,
각각 메서드가 픽스처 모두 갖고있는게 좋을 것 같아서 해당 메서드 삭제했습니다!

2022-10-16 10:21 UTC, JangBomi commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageFileShareServiceTest.java
>                  "text", text,
해당 메서드를 사용하는 테스트가 text값이 없을때들을 parameterizedTest로 테스트한거라 외부에서 text 받아준거였어요!

2022-10-17 04:22 UTC, hyewoncc approved these changes
변경된 파일이 정말 많네요 😵 수고로운 작업이었을텐데 고생많았어요, 봄! 
이미 연로그가 리뷰 충분히 달아주셔서 가벼운 의견만 남겼습니다 
멤버 픽스쳐에서 로그인 여부에 따라 생성자 아예 분리한 부분 정말 좋네요 
approve  할게요!

2022-10-17 04:22 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/channel/domain/ChannelSubscriptionTest.java
> +        Member member = new Member("slackId", "유저 이름", "Profile.png", workspace);
저는 테스트 대상 도메인을 제외하고 픽스쳐를 쓰는 쪽이 테스트 대상이 더 명확하게 보일 것 같아요!

2022-10-17 04:22 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/fixture/MemberFixture.java
>      }
저도 연로그 의견에 동의합니다! 
`createNeverLoggedIn` `createLogin` 이런 방식은 어떨까요 ?

2022-10-17 04:22 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageChangedServiceTest.java
> -            "메시지 전송!",
원래 제가 리팩토링 했어야 했던 부분 같은데.. 👀💦💦 고마워요 봄!!!

2022-10-17 04:24 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/channel/domain/ChannelSubscriptionTest.java
> +        Member member = new Member("slackId", "유저 이름", "Profile.png", workspace);
기왕 있는거 사용하면 편할 것 같아요😄

2022-10-17 04:25 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/fixture/MemberFixture.java
>      }
createFirstLoginMember, createMember 같은건 어떨까요?
createFirstLogin, create도 괜찮을 것 같네요!

2022-10-17 04:26 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/slackevent/application/message/MessageFileShareServiceTest.java
>                  "text", text,
아!! 이해했습니다 굿~~~`

2022-10-17 04:26 UTC, yeon-06 approved these changes
안녕하세요 봄 
피드백 꼼꼼하게 반영해주셔서 감사합니다 ㅎㅎㅎ
고생하셨습니다😄👍

2022-10-17 04:42 UTC, JangBomi commented on backend/src/test/java/com/pickpick/fixture/MemberFixture.java
>      }
createNeverLoggedIn, createLogin으로 수정했습니다!

2022-10-17 04:47 UTC, merged