refactor: 리마인더 도메인과 연관 예외, DTO 리팩터링
woowacourse-teams/2022-pickpick pull request #618
Opened 2022-10-17 06:45 UTC by hyewoncc

## 요약

- 리마인더 도메인에 검증 로직 적용
- 리마인더 수정 관련 커스텀 예외 개선
- 리마인더 수정/생성 요청 DTO명 변경

<br>

## 작업 내용

- 리마인더 도메인에 검증 로직 적용
  - 리마인더 생성/수정 시, 리마인더 시각이 현재 시간보다 과거일 경우, `BadRequestException`을 상속한  `ReminderInvalidDateException`을 발생시킵니다
  - 로깅 메시지는 이렇게 남습니다  
  <img width="903" alt="스크린샷 2022-10-15 오후 2 59 05" src="https://user-images.githubusercontent.com/80666066/196105452-8c84faa6-ae64-4729-85d4-e770da0f821f.png">  
- 리마인더 수정 관련 커스텀 예외 개선
  - 일치하는 memberId, messageId가 없을 시, `ReminderNotFoundException`을 발생시키도록 하고, `ReminderUpdateFailureException`을 삭제했습니다  
 - 리마인더 수정/생성 요청 DTO명 변경
   - `ReminderSaveRequest` -> `ReminderRequest`로 변경했습니다  

<br>

## 참고 사항

`ReminderServiceTest`중 **리마인더 조회 시 과거 리마인더는 조회되지 않는다**를 삭제했는데요,  
생성 로직에 시간 검증이 들어가면서 과거 시각의 리마인더를 자바 코드에서 저장할 방법이 사라졌기 때문입니다 😅 

이를 `MessageServiceTest`처럼 `Clock` 모킹으로 처리하려고 했는데,  
1. `ReminderServiceTest`의 라이프사이클이 클래스 단위로 설정되어 있음
2. 그래서 `Clock` 모킹이 필요한 건 한 테스트 뿐인데, 여기서 모킹한다면 다른 테스트에서는 다 `LocalDataTime.now()`를 모킹해줘야 됨
3. 그냥 라이프 사이클을 바꾼다면 이 테스트 하나 때문에 비용이 많이 들게 됨  

이런 이유로 일단 해당 테스트를 삭제했습니다 
테스트를 하는 게 맞는 것 같은데, 적절한 다른 방법이 생각나면 다시 추가해볼게요 🥲 제안주시면 감사합니다  
현재는 저 경우만 따로 테스트를 `@Nested` 외부로 뺀다 밖에 떠오르지 않네요   

<br>

## 관련 이슈

- Close #602

2022-10-18 06:20 UTC, yeon-06 requested changes
안녕하세요 써머!
리팩터링 고생하셨어요🎉
코멘트는 별로 없는데 개선 후 코드를 확인하고 싶어서 RC로 남겼습니다😄

2022-10-18 06:20 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
> -        @DisplayName("현재 시간보다 과거의 리마인더는 조회되지 않는다")
앗 지금 다시 보니 임시(?)로 삭제하신거였군요
모킹을 완전히 제거하는게 아닌 이상 해당 클래스에서 모킹을 제거한다고 의미가 있는지 잘 모르겠어요ㅜ.ㅜ

2022-10-18 17:52 UTC, JangBomi requested changes
써머 리뷰가 늦었네요 ㅠㅠ
검증 로직이 꼼꼼해져서 좋아요!! 검증에 대한 테스트도 꼼꼼하게 추가해주신 점 최고 👍 

테스트에서 Channel을 생성할 때 `create(workspace)` 형태로 채널 생성해줘야하는 부분 하나때문에 우선 RC 합니다! 

써머 짱 ⛱️ 🌞 👍 ❤️

2022-10-18 17:52 UTC, JangBomi commented on backend/src/test/java/com/pickpick/message/domain/ReminderTest.java
> +        Message message = PLAIN_20220715_17_00_00.create(notice, hope);
이 부분 채널 생성 NOTICE.create(jupjup)으로 해야할 것 같아요!

2022-10-18 17:52 UTC, JangBomi commented on backend/src/test/java/com/pickpick/message/domain/ReminderTest.java
> +        Message message = PLAIN_20220715_17_00_00.create(notice, hope);
여기 채널도 NOTICE.create(jupjup) 로 수정해야할 것 같습니다!

2022-10-18 17:52 UTC, JangBomi commented on backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
> +            Channel notice = channels.save(NOTICE.create());
여기도 NOTICE.create(jupjup)로 수정해야해용!!

2022-10-18 17:52 UTC, JangBomi commented on backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
> -        @DisplayName("현재 시간보다 과거의 리마인더는 조회되지 않는다")
이 부분 고민해봤는데 지금 당장은 어떻게 하는게 좋을지 잘 모르겠네요 😭 좀 더 고민해보고 좋은 방법 생각나면 다시 코멘트 달겠습니다!
별개로 혹시 임시(?)로 삭제하신거라면 삭제 말고 `@Disabled("도메인에 과거 시간 검증 로직이 추가되어 과거 시간 테스트 불가")` 라고 명시해두는거 어떨까요? 만약 삭제한채로 머지된다면 나중에 기억에서 잊혀질까봐 의견 내봅니다!

2022-10-19 01:18 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/exception/message/ReminderInvalidDateException.java
> +                        SERVER_MESSAGE, LocalDateTime.now().format(pattern), remindDate.format(pattern)),
맞는 말이네요!!! `LocalDateTime.now()`를 변수에 할당했다가 사용하도록 정정했습니다

2022-11-13 08:27 UTC, hyewoncc commented
오프라인으로 얘기했었는데 우선 순위가 밀리는 것 같아서 일단 close 하겠습니다 🥲 
더 기깔나는 방안이 생기면 다시 가져올게요

2022-11-13 08:27 UTC, closed without merging