refactor: 워크스페이스 개인화 작업 이후 테스트코드 리팩토링 및 slackClient 모킹 제거
woowacourse-teams/2022-pickpick pull request #627
Opened 2022-10-18 17:16 UTC by JangBomi

## 요약

워크스페이스 개인화 작업 이후 테스트코드 리팩토링 및 slackClient 모킹 제거
<br><br>

## 작업 내용

- 워크스페이스 개인화 작업을 하면서 우선은 돌아가게 만들어놨던 테스트코드들을 리팩토링했습니다.
- 논의한대로 AuthService의 registerWorkspace와 login을 분리했습니다.
- 모든 methodsClient 모킹을 제거하고 fakeClient가 해당 역할을 대신하는 Test Double 이 되도록 구현했습니다.

기타 코드에 대한 설명은 커멘트로 달아두겠습니다!

<br><br>

## 참고 사항

- 테스트코드에서 `@MockBean MethodsClient methodsClient` 를 제거하여 현재 테스트에서 뜨는 스프링 컨텍스트 개수가 7개 -> 6개로 감소했습니다!! 

추정하기로는 6개의 context는
- PickpickApplicationTest
- AccpetanceTest
- ControllerTest
- ServiceTest 전체
- BookmarkServiceTest -> @MockBean DateTimeProvider
- MessageServiceTest -> @SpyBean Clock 
이렇게 6개가 뜨는 것 같습니다. 참고차 적어둡니다.  

<br><br>

## 관련 이슈

- Close #606 

<br><br>

2022-10-18 17:23 UTC, JangBomi commented on backend/src/test/java/com/pickpick/fixture/StubSlack.java
> +
FakeClient를 `fake` 라는 이름대로, 최대한 동작을 구현하게 만들고싶었어요.
그래서 생각해낸게 `StubSlack` 이고, 슬랙처럼 동작하게 하게 했습니다.

2022-10-18 17:25 UTC, JangBomi commented on backend/src/test/java/com/pickpick/fixture/StubSlack.java
> +    }
login, registerworkspace에서 필요한 `code` 는 슬랙의 OAuth 과정 중에 슬랙이 발급해주는 코드입니다. 
이 동작을 가짜로 구현해봤어요.

2022-10-18 17:26 UTC, JangBomi commented on backend/src/test/java/com/pickpick/fixture/StubSlack.java
> +
이 부분은 유저가 슬랙에서 직접 채널에 참여하는 부분입니다

2022-10-18 17:27 UTC, JangBomi commented on backend/src/test/java/com/pickpick/support/FakeClient.java
> +
기존에는 FakeClient가 `Dummy` 의 느낌이었던 것 같아요. 좀 더 `Fake` 의 느낌으로 내부 구현을 가지도록 변경해봤습니다!

2022-10-19 01:38 UTC, yeon-06 requested changes
안녕하세요 봄~!
SlackClient 모킹 제거되는게 감동이네요🥺

몇 가지 제안사항이 있어 RC로 남깁니다
추가로 저희 이번 PR에서 변수명을 `slackClient` -> `externalClient`로 변경하는건 어떨까요?

2022-10-19 01:38 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/fixture/StubSlack.java
> +
StubSlack이랑 FakeClient랑 헷갈리는 것 같아요ㅠ_ㅠ
해당 클래스의 내용이나 데이터들을 FakeClient로 옮기는게 어떤가요?
클래스가 분리되어 있으니까 StubSlack와 FakeClient 둘 다 로직을 완전히 이해하고 있어야 신규 테스트 코드를 짤 수 있을 것 같아요ㅠ.ㅠ 
변수와 메서드 그대로 가져간 뒤에 테스트에서는 `@Autowired FakeClient fakeClient;`로 사용하면 될 것 같아요!

2022-10-19 15:28 UTC, JangBomi commented on backend/src/test/java/com/pickpick/fixture/StubSlack.java
> +    }
전체적으로 memberCode -> code로 모두 이름 변경했습니다!

2022-10-19 15:52 UTC, JangBomi commented on backend/src/test/java/com/pickpick/fixture/ChannelFixture.java
> +    private final boolean isJupjupChannel;
다시 원래대로 defaultChannel로 바꿨습니다! boolean 변수라 defaultChannel보다 isDefaultChannel이 좀 더 직관적일 것 같아서 앞에 is만 붙여줬어요 :)

2022-10-19 16:14 UTC, JangBomi commented on backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
> +    @Transactional
` assertThat(savedKkojae.getWorkspace()).isEqualTo(savedJupjup);` 이 부분에서 `savedKkojae.getWorkspace()` , 꼬재의 workspace 호출 시에 트랜잭션이 없으면 lazy loading 때문에 
`org.hibernate.LazyInitializationException: could not initialize proxy [com.pickpick.workspace.domain.Workspace#1] - no Session` 이 뜨더라고요.

워크스페이스 초기화 후 `해당 워크스페이스의 유저 목록 불러오기` 와 같은 기능이 구현되어있다면 그걸로 검증하면 되는데, 기능이 구현되어있지 않아서 저장되어있는 꼬재의 워크스페이스를 호출하면서 문제가 발생하는데 이 상황을 어떻게 해결해야할지 모르겠어서 우선 @Transactional을 넣었습니다.

혹시 좋은 방법 있을까요?ㅜㅜ

2022-10-19 16:14 UTC, JangBomi commented
- [x] StubSlack 제거 후 FakeClient 내부에서 해결할 수 있도록 통일
- [x] ParticipationFixture 생성
- [x] 전체적으로 MemberCode -> code로 수정
- [ ] AuthServiceTest에서 @transactional 제거 -> 방법 고민중ㅠㅠ
- [x] MessageFixtures -> MessageFixture로 이름 변경
- [ ] 머지 충돌 해결

2022-10-19 16:16 UTC, JangBomi commented on backend/src/test/java/com/pickpick/fixture/MemberFixture.java
> +    public String getCode() {
이것도 고민이에요. 코드 리뷰 반영 후의 코드에 `getMemberSlackIdByCode` 도 추가되는 등 원래라면 슬랙이나 다른 객체가 해줘야할 역할을 대신해주는 기능이 이곳저곳에 있는데, 더 좋은 방법이 잘 안떠오르더라고요 ㅠㅠ
연로그라면 어떻게 해결하실까요?

2022-10-20 02:06 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/acceptance/AcceptanceTestBase.java
> +    protected String 코드로_멤버의_SlackId_추출(final String memberCode) {
code에서 slackId 정보를 가져올 수 있다라고 오해하게 되는 것 같아요!
원래 과정을 거칠 수 있다면 거치는게 좋을 것 같아요😄

2022-10-20 02:08 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
> +        jwtToken = 로그인_응답에서_토큰_추출(loginResponse);
아 저희 slack에서 쓰는 token이 추가되어서 그렇군요😵!!!
그렇다면 저는 jwtToken도 괜찮은 것 같아요!

2022-10-20 02:15 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/fixture/MemberFixture.java
> +    public String getCode() {
저라면 util이나 support 같은 클래스를 새로 생성해서 해당 메서드를 static import 하여 사용할 것 같아요!

2022-10-20 02:17 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/fixture/MemberFixture.java
> +    public String getCode() {
원래는 code 발급이 Slack에서 하는 기능이니까 FakeClient에 메서드를 넣고 FakeClient를 주입 받아 쓸 수도 있을 것 같아요👀

2022-10-20 02:32 UTC, yeon-06 approved these changes
안녕하세요 봄
정말 수고스러운 작업들이었는데 고생 많으셨습니다🥺
approve 할게요❤

![image](https://user-images.githubusercontent.com/53105735/196842279-ef39830f-e24b-4a81-81a6-f2b81c47a910.png)

2022-10-20 02:52 UTC, hyewoncc approved these changes
테스트가 훨씬 테스트 다워진 것 같아요!!
봄 너무 고생 많았습니다 
코멘트는 꼭 반영하지 않아도 되는 것들이라 approve 할게요~

2022-10-20 02:52 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/acceptance/AcceptanceTestBase.java
> +    protected String 코드로_멤버의_SlackId_추출(final String code) {
`SlackId` -> `slackId`?!

2022-10-20 02:52 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/acceptance/channel/ChannelAcceptanceTest.java
> +        String token = 로그인_응답에서_토큰_추출(loginResponse);
<img width="516" alt="image" src="https://user-images.githubusercontent.com/80666066/196843577-6f0560d6-35ae-4d61-a802-08ff216a7b9d.png">

2022-10-20 02:52 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
> +        Member summer = members.save(SUMMER.createLogin(jupjup));
이건 왜 저로 바꾸셨죠?! ㅋㅋㅋ

2022-10-20 02:52 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/fixture/MemberFixture.java
> +    public String getCode() {
전 `MemberFixture`가 정확히 말하면 `Member` 도메인이 아니라, `Member` 도메인과 관련된 고정값을 `enum`으로 모아두는 개념이라 생각해서 여기에 `code`가 있어도 괜찮다고 생각합니다! 
물론 `FakeClient`에 넣어도 좋고요

2022-10-20 02:52 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/fixture/ParticipationFixture.java
> +public enum ParticipationFixture {
👍

2022-10-20 06:44 UTC, JangBomi commented on backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
> +        Member summer = members.save(SUMMER.createLogin(jupjup));
제 마음입니다 ❤️

2022-10-20 06:47 UTC, JangBomi commented on backend/src/test/java/com/pickpick/fixture/MemberFixture.java
> +    public String getCode() {
이 부분은 좀 더 고민해볼게요!!

2022-10-20 06:57 UTC, JangBomi commented on backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
> +        jwtToken = 로그인_응답에서_토큰_추출(loginResponse);
로그인을 위한 토큰은 token으로 냅두고,
Member 도메인 내부에서 슬랙이 발급해주는 토큰을 slackToken으로 수정했습니다!

2022-10-20 07:10 UTC, merged