feat: 워크스페이스 등록 후 바로 로그인
woowacourse-teams/2022-pickpick pull request #677
Opened 2022-10-26 06:07 UTC by yeon-06

## 요약

워크스페이스 등록 후 바로 로그인

<br><br>

## 작업 내용

워크스페이스 등록 후 바로 로그인이 가능하도록 구현했습니다.
트랜잭션 설정 관련 자세한 내용은 issue에 등록하겠습니다.

<br><br>

## 관련 이슈

- Close #675 

<br><br>

2022-10-26 08:20 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/workspace/ui/WorkspaceController.java
> +        return authService.login(memberInfoDto);
예전에 봄이 제시한 제안인데요
'로그인에 실패해도 워크스페이스에 등록된 정보는 저장되어야할 것 같다'

이 때문에 로직이 두 개로 분리되어 두 서비스에서 각각의 메서드를 호출하도록 구현했습니다.

2022-10-26 08:21 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/auth/application/dto/WorkspaceInfoDto.java
> +                            final String userToken, final String userSlackId) {
WorkspaceInfoDto에서 이제 유저에 대한 정보도 담게 되었는데요
적당한 네이밍이 생각나지 않아 일단 두었습니다 
이름 추천 부탁드려요😭

2022-10-26 15:32 UTC, hyewoncc requested changes
🪁로그... 구현부터 테스트 수정이랑 추가까지 고생했어요 🥺 
리뷰는 컨벤션 관련이 대부분인데, 머지하기 전에 자잘하게 확인하고 싶어서 일단 `RC`로 남길게요!

2022-10-26 15:32 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/auth/application/dto/WorkspaceInfoDto.java
> +                            final String userToken, final String userSlackId) {
슬랙에서 호출하는 메서드 명이 `oauthV2Access()` 더라고요..?
`OAuthAccessInfoDto`는 어떨까요?!

2022-10-26 15:32 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/workspace/application/WorkspaceService.java
> +
워크스페이스 등록 / 로그인 별도 진행으로 서비스 클래스가 추가되었군요 
가벼운 수정이라 생각했는데 많은 작업을 하셨네요 🥺 
고생많았어요 연로그~

2022-10-26 15:32 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/workspace/application/WorkspaceService.java
> +
메서드 선언 순서와 사용 순서가 불일치하네요!

2022-10-26 15:32 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/workspace/application/WorkspaceService.java
> +        }
메서드 명만 먼저 봤을 땐  "존재하는 워크스페이스인지 확인한다"로 읽혔어요 
`validateWorkspaceNotExists`는 어떨까요? 
NotExists는 슬랙에도 존재하지 않는다... 하는 느낌이 들긴 해서 
`validateWorkspaceNotRegistered` 가 나은 것 같기도 하네요

2022-10-26 15:32 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/workspace/application/WorkspaceService.java
> +    public MemberInfoDto registerWorkspace(final String code) {
그냥 `register()`라고 해도 되지 않을까요?!

2022-10-26 15:32 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/acceptance/workspace/WorkspaceAcceptanceTest.java
> +@DisplayName("인증 & 인가 인수 테스트")
✂️ 🩹 하다가 변경을 깜빡하셨군요..🤭

2022-10-26 15:32 UTC, hyewoncc commented on backend/src/test/java/com/pickpick/workspace/application/WorkspaceServiceTest.java
> +        assertThat(afterSave).isNotEmpty();
```suggestion
        assertThat(afterSave).isPresent();
``` 
오 suggestion 기능 처음써보는데 좋네요

2022-10-27 02:07 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/auth/application/dto/WorkspaceInfoDto.java
> +                            final String userToken, final String userSlackId) {
오 좋은 것 같아요!!!👍👍

2022-10-27 02:08 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/workspace/application/WorkspaceService.java
> +    public MemberInfoDto registerWorkspace(final String code) {
앗 맞네요!! 반영하겠습니다~!

2022-10-27 02:09 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/acceptance/workspace/WorkspaceAcceptanceTest.java
> +@DisplayName("인증 & 인가 인수 테스트")
😨

2022-10-27 06:39 UTC, JangBomi requested changes
리뷰 및 의견 남겨용!! 의견 듣고싶은거 있어서 일단 RC 남겨요!!

2022-10-27 06:39 UTC, JangBomi commented on backend/src/main/java/com/pickpick/workspace/ui/WorkspaceController.java
> +        return authService.login(memberInfoDto);
그냥 의견입니다! 요즘 코드리뷰에서 많이 보이는 rca룰에서 a에 해당하는 의견이에용.
--
`workspace.regsiterWorkspace()` 라는 메서드 호출의 결과가 `MebmerInfoDto` 인게 뭔가 오잉 🤔 하는 생각이 드는 것 같아요. 워크스페이스를 등록하는 메서드인데 멤버에 대한 정보를 반환해주네? 라는 생각이 들었어요!
개선방안 생각해봤을 때는 
- registerWorkspace의 메서드 명 바꾸기 
- MemberInfoDto의 클래스명 바꾸기 
-  WorkspaceInfoDto의 이름이 `OAuthAccessInfoDto ` 로 바뀐다면 `authService.login()`의 파라미터로 `OAuthAccessInfoDto `를 사용해주기 

이렇게 세 가지 생각이 났는데 셋 다 마땅히 구체화된 해결방안은 생각이 나지 않네요ㅠㅠ

2022-10-27 06:39 UTC, JangBomi commented on backend/src/main/java/com/pickpick/support/SlackClient.java
>          OAuthV2AccessResponse response = callOAuth2(code, slackProperties.getLoginRedirectUrl());
위 메서드명 바꿀 때 이 메서드명도 바꾸면 좋을 것 같아요.
일단 이 메서드 자체가 MemberSlackID만 반환하는 메서드가 아니라 위에 써머 의견이랑 같이 간다면 callOAuthAccessToMember 정도 이름어떨까? 싶네용. 제가 만든 메서드 이름이었는데 이 때 메서드 이름 수정해야지~ 하고 잊었어서 이번 PR에서 부탁드려요!

2022-10-27 06:39 UTC, JangBomi commented on backend/src/main/java/com/pickpick/support/SlackClient.java
>          OAuthV2AccessResponse response = callOAuth2(code, slackProperties.getLoginRedirectUrl());
이건 그냥 써머와 연로그의 의견 듣고싶어서 댓글 남겨요
--
 externalClient에서 (현재 메서드명 기준으로) `callWorkspaceInfo` 와 `callMemberSlackIdByCode`를 분리하는게 맞을까? 하는 의문이 살짝 들었어요. 
두 메서드 다 `callOAuth2()`를 호출하고 다른 점은 어떤 Dto를 만드는가 인 것 같은데, 
- `어떤 DTO를 반환해주는가 를 결정하는게 externalClient의 역할인가?`
- `슬랙에서 oauthv2access 메서드를 넘겨줄 때 null값으로 넘어오는 것도 있으니까 externalClient에서 값 조립해주는 것 까지 역할이다`

이렇게 두 생각이 들었는데 이 부분에 대해서 써머와 연로그의 생각도 궁금해서 댓글 남겨용

2022-10-27 06:39 UTC, JangBomi commented on backend/src/main/java/com/pickpick/workspace/application/WorkspaceService.java
> +
분리하니 한 서비스가 갖는 의존성이 줄어서 좋네요!! 최고 👍

2022-10-27 06:39 UTC, JangBomi commented on backend/src/main/java/com/pickpick/workspace/application/WorkspaceService.java
> +        }
`validateUnregisteredWorkspace` 의견도 살짝 던지고갑니당

2022-10-27 06:39 UTC, JangBomi commented on backend/src/test/java/com/pickpick/acceptance/workspace/WorkspaceRestHandler.java
> +    }
워크스페이스 초기화 + 로그인 두 작업을 모두 하는거니 메서드 이름을 `워크스페이스_초기화_및_로그인` 으로 하는건 어떨까요? 
![image](https://user-images.githubusercontent.com/55357130/198209089-ba1ee9c6-0fe5-47af-bc97-78a526e0a584.png)

채널 인수테스트 같은 곳에서는 워크스페이스 초기화만 있고 로그인 과정이 없는 것 같은 느낌이 들어요!

2022-10-27 06:44 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/support/SlackClient.java
>          OAuthV2AccessResponse response = callOAuth2(code, slackProperties.getLoginRedirectUrl());
저는 `externalClient`의 추상화된 역할이 각각 워크스페이스 정보 가져오기, 멤버 정보 가져오기 라고 생각해서 이 내부를 `SlackClient`가 어떤 식으로 구현하는지는 상관없다고 생각해요! 
그럴 리는 없지만 만약 `KakaoClient`가 추가된다면 거기서는 각각 다른 api를 호출 할 수도 있겠죠 
하지만 `externalClient`를 사용하는 입장에서는 알 필요 없으니까요

2022-10-27 06:46 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/workspace/ui/WorkspaceController.java
> +        return authService.login(memberInfoDto);
저는 바꾼다면 마지막 방안이 제일 직관적인 것 같아요!

2022-10-27 07:48 UTC, JangBomi commented on backend/src/main/java/com/pickpick/support/SlackClient.java
>          OAuthV2AccessResponse response = callOAuth2(code, slackProperties.getLoginRedirectUrl());
아하 써머 의견 들으니 확 생각이 정리됐어요. ❤️ 
메서드 이름만 callMemberSlackId에서 변경하면 좋을 것 같아요!!!!!

2022-10-27 09:35 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/support/SlackClient.java
>          OAuthV2AccessResponse response = callOAuth2(code, slackProperties.getLoginRedirectUrl());
👍
이름은 slackId뿐 아니라 token도 가져오고 있기 때문에 callMemberInfo로 변경했습니다!

2022-10-27 10:56 UTC, JangBomi commented on backend/src/main/java/com/pickpick/auth/application/AuthService.java
> +        Member member = members.getBySlackId(memberSlackId);
아까 말했던게 딱 이거였어요!! 알잘딱깔쎈 짱 👍

2022-10-27 10:57 UTC, JangBomi approved these changes
🪁 로그 최고 !! 👍 👍 👍 저는 approve 합니닷!!!

2022-10-28 00:13 UTC, hyewoncc approved these changes
🪁✍️!! 피드백 반영하신 것 확인했어요!!
저도 approve 합니다, 수고많으셨어요~

2022-10-28 00:21 UTC, merged