refactor: 메시지 서비스에서 Querydsl 로직 분리
woowacourse-teams/2022-pickpick pull request #678
Opened 2022-10-26 08:53 UTC by hyewoncc

## 요약

메시지 서비스에서 Querydsl 로직 분리  

<br>

## 작업 내용

- `Querydsl`이 사용되는 모든 로직을 별도의 `QMessageRepository` 클래스로 분리  
- `QMessageRepository`의 메서드를 JPA 레포지토리 메서드 명명 규칙과 비슷하게 개선  
- `MessageRequest`가 레포지토리 레이어까지 넘어가지 않도록 파라미터 분리  

<br>

## 관련 이슈

추후 등록  

<br>

2022-10-26 09:12 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/application/MessageService.java
> +                messageRequest.getMessageCount());
`MessageRequest`라는 DTO가 레포지토리까지 넘어가면 레포지토리가 클라이언트에서 넘어오는 값을 알고 있는 상황이 되는 것 같아서, 파라미터에 값을 꺼내서 넣도록 했습니다  
조금 너저분한 감이 없지 않지만 `jpaQueryFactory` 로직보다는 짧으니까 이게 낫지 않을까요...👀

2022-10-26 09:12 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/domain/QMessageRepository.java
> +                .fetch();
가독성 개선을 위해 JPA 메서드 명명 규칙을 최대한 모방해봤어요

2022-10-27 02:17 UTC, yeon-06 approved these changes
안녕하세요 써머~!
분리 정말 고생 많으셨습니다
MessageService가 깔끔해진 것을 보니까 감탄이 나오네요👍
메시지 조회 쪽은 언제봐도 조건이 복잡하군요😔

2022-10-27 02:17 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/message/application/MessageService.java
> +        return channelIds != null && !channelIds.isEmpty();
꼼꼼한 개선👍

2022-10-27 02:17 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/message/domain/QMessageRepository.java
> +
2줄!

2022-10-27 09:13 UTC, JangBomi requested changes
써머 👍 
MessageService에서 QueryDsl이 빠지니까 정말 깔끔해요 👍 👍 👍 👍 👍 최고의 개선
리뷰 몇개 남겼고, 답을 보고싶어서 우선 RC할게요!! 

![image](https://user-images.githubusercontent.com/55357130/198243951-c6db3495-4449-4f4d-a7b0-8b62410cd1de.png)

2022-10-28 00:14 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/application/MessageService.java
> +        return channelIds != null && !channelIds.isEmpty();
이렇게 적는 게 확실하겠네요! 반영하겠습니다

2022-10-28 00:16 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/application/MessageService.java
>                            final ChannelSubscriptionRepository channelSubscriptions,
거기서 둘 다 사용한다면 `QRepository` 인터페이스 추출 후 상속하는 식으로 하나의 레포만 쓸 수 있게 해야겠네요 
설명이 어려운데 또 블로그 홍보같아졌지만!!.. [제 블로그 글 초반](https://hyewoncc.github.io/querydsl-refactoring/)에 해당 방식이 설명되어있어요

2022-10-28 00:17 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/application/MessageService.java
>                            final ChannelSubscriptionRepository channelSubscriptions,
선언 순서는 변경할게요!

2022-10-28 00:22 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/domain/QMessageRepository.java
> +                                              final String keyword,
Response 까지는 생각 못했는데 정말 좋은 접근이네요!! 
그런데 별도의 dto를 만들어도 Response랑 내부가 동일하게 될 것 같은데 좀 더 효율적인 방안이 있을까요?

2022-10-28 00:30 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/domain/QMessageRepository.java
> +    private final QMessage message = QMessage.message;
사용되는 순서대로 재정렬 했습니다~

2022-10-28 00:30 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/message/domain/QMessageRepository.java
> +                        .fetchOne())
😁 이유 없어요! 확실히 추출하는게 낫네요

2022-10-28 05:56 UTC, JangBomi commented on backend/src/main/java/com/pickpick/message/application/MessageService.java
>                            final ChannelSubscriptionRepository channelSubscriptions,
아하 이해했습니다! 👍

2022-10-28 05:59 UTC, JangBomi commented on backend/src/main/java/com/pickpick/message/domain/QMessageRepository.java
> +                                              final String keyword,
음...그러게요 어ㄷ쨋든 반환하는 그대로니 내용은 똑같을 것 같네요 ㅠㅠ
도메인과 request가 동일하더라도 도메인을 view에 노출시키지 않기위해 controller에서 dto를 사용하는것처럼 그냥 내용이 같은 새로운 객체 만들어서 ResponseDto 자체를 repository단까지 들어가게 하지 않는다는 것에 대한 의의만 있을 것 같네요!!
이 부분은 다른 Service도 옮기면서 차차 같이 생각해봐용!!!

2022-10-28 05:59 UTC, JangBomi approved these changes
댓글 달아신거 확인했어요! approve 하겠습니당 👍

2022-10-28 05:59 UTC, merged