refactor: 메시지 text에서 멘션 아이디를 대체하는 부분 리팩토링
woowacourse-teams/2022-pickpick pull request #693
Opened 2022-11-01 03:57 UTC by JangBomi

## 요약

메시지 text에서 멘션 아이디를 대체하는 부분 리팩토링

<br><br>

## 작업 내용

메시지 text에서 멘션 아이디를 대체하는 부분 리팩토링

<br><br>

## 참고 사항

아직 미완이지만 기록해야할 부분이 있어서 Draft로 PR 올립니다.

### 현재 코드
- ResponseDto가 MessageTextResponses, MessageTextResponse 인터페이스를 구현하도록 하고, 타입을 제네릭으로 구성
- `@MentionIdReplaceable` 어노테이션을 도입해 해당 어노테이션이 붙은 메서드는 반환 값의 메시지 텍스트에서 멘션 아이디가 등장하면 닉네임으로 대치하는 코드가 동작하도록 Aspect 도입

### 현재 코드의 장점
- 깔끔하게 멘션 아이디를 닉네임으로 대치하는 로직을 조회 로직에서 빼냈다는 생각이 들어요.
<img width="660" alt="image" src="https://user-images.githubusercontent.com/55357130/199008823-6179ab74-44e2-48f2-9fdb-b46f4c670552.png">
- 개선된 코드인데, 어노테이션의 사용만으로 멘션 아이디를 대체할 수 있다는게 매력적임
- 빈 주입을 할 필요가 없음

### 현재 코드의 단점
- ResponseDto는 말그대로 DTO라 값을 전달하는 역할만 해야할 것 같은데, MessageTextResponse, MessageTextResponses라는 인터페이스를 구현하면서 명세가 생긴 느낌이라 DTO 본래의 역할을 하지 못하는 것 같음. 
- 중복 로직을 제거하기 위해 코드의 복잡도가 올라간 것 같음

### 멘션 아이디를 닉네임으로 대치하는게 AOP로 뺄만한 기능일까?
이 부분은 이전에 연로그가 닉네임 대치가 AOP로 뺄만한 기능인가? 라고 이야기해줘서 좀 더 깊게 고민해볼 수 있었어요.
공통 로직과 횡단 관심사의 관점으로 봤을 때 각 Service가 아래 그림에서의 핵심 로직이고, 멘션 아이디를 대체하는 로직은 핵심로직을 관통하는 횡단관심사라고 생각했어요.
MessageService, ReminderService, BookmarkService 의 각 find() 또는 findOne() 메서드의 관심사는 `Request에 넘어오는 조회 조건에 맞게 조회하는 것` 이지, `텍스트의 멘션 아이디를 닉네임으로 대치하는 것`은 핵심 관심사가 아니라고 생각이 들었고, 횡단 관심사로 뺄 수 있는 영역이 아닐까? 라고 생각했어요.
<img width="830" alt="image" src="https://user-images.githubusercontent.com/55357130/199018311-c41db7bb-36ab-4bf3-9dd5-2e707bf0ec5c.png">

 너무 멘션아이디를 Aspect로 보는 관점에 매몰되어있나? 싶어서 Aspect를 사용 안하고 [제네릭 없이 최대한 중복 로직 제거한 버전](https://github.com/woowacourse-teams/2022-pickpick/tree/feature/refactor-mentionid)과 [제네릭 사용하고 중복 로직 제거한 버전](https://github.com/woowacourse-teams/2022-pickpick/tree/feature/refactor-mentionid-with-generic) (각 브랜치에 ReminderService쪽 보시면 가장 보기 편할 것 같아요!) 도 구현해보면서 어떤 방법이 가장 좋을까 고민해봤을 때도 멘션아이디를 대체하는 부분은 횡단관심사라는 생각이 들었습니다!

### 아무튼 그래서 이 코드의 개선 방향은
- Dto가 인터페이스를 구현하지 않도록 수정
이 될 것 같아요. 어제 써머랑 이야기하면서 DTO가 인터페이스를 구현하는게 이상하다, 인터페이스가 있는건 명세가 생긴건다. 인터페이스를 구현하고 제네릭을 사용한건 쉬운 방법을 돌아간 것 같다. 라는 이야기를 나눴어서 우선 이 코드를 리플렉션으로 개선할 예정입니다.
현재 코드는 ResponseDto가 MessageTextResponse를 구현한 경우에 대해 @MentionIdReplaceable을 붙이면 멘션 아이디 대체 코드가 동작하는데, 도메인 정책이 복잡한 것 같아서 리플렉션으로 필드 가져와서 수정해주는게 낫겠다 싶었어요.

~~그냥 제가 AOP로 테코톡해서 어떻게든 한 번 적용해보고 이력서에 적으려고 집착하는 것 같긴한데....^_^.....~~

Draft PR이고 아직 리플렉션 적용해보기 전이지만 혹시라도 의견 있으시다면 코멘트로 남겨주세요!! 바쁘실텐데 감삼당 🙇‍♀️ 

<br><br>

## 관련 이슈

- Close #648 

<br><br>

2022-11-02 11:23 UTC, JangBomi commented
### 위의 개선방향에 적은대로 리팩토링 완료했습니다. 😊
- DTO가 인터페이스 구현하던 것 삭제
- 제네릭 삭제
- 리플렉션 도입 -> 내부에 필드로 "text"를 가지면 해당 필드의 값을 새로 세팅해줍니다 
- DTO 내부에서 어찌보면 비즈니스 로직인 `replaceText()` 삭제

2022-11-09 04:42 UTC, yeon-06 requested changes
안녕하세요 봄!
리뷰가 많이 늦어졌습니다ㅜ0ㅠ
몇 가지 코멘트를 남겼으니 확인 부탁드려요 <3

2022-11-09 04:42 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/message/application/MessageService.java
> +    @MentionIdReplaceable
로직이 확 줄어들긴 했네요👍

2022-11-09 04:42 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/support/MentionAspect.java
> +        this.slackIdExtractor = slackIdExtractor;
SlackIdExtractor를 bean으로 주입받을 필요가 있을까?
그냥 util 클래스로 내부 메서드들을 static 으로 만든 뒤 호출해도 되지 않을까?
라는 고민이 들긴 하네요🤔

util성 클래스를 만들면 간편하게 사용할 수 있지만 테스트 시 밀접한 관계를 갖게 되긴 합니다
어떤게 더 좋다라는 생각은 딱히 안들고 트레이드 오프 같네요!
그냥 이런 생각도 있구나 봐주시고 편하신 쪽으로 선택해주세요😊

2022-11-09 04:42 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/support/MentionAspect.java
> +        List<Member> workspaceMembers = members.findAllByWorkspace(member.getWorkspace());
요 리뷰도 확인 부탁드려요😄
https://github.com/woowacourse-teams/2022-pickpick/pull/641#discussion_r1000055168

2022-11-09 04:42 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/support/MentionAspect.java
> +                .filter(field -> field.getType().equals(List.class))
혹시 field.setAccessible이 먼저 호출되어야하는 메서드일까요?
그게 아니라면 filter를 거친 후에 peek하는 것이 더 좋을 것 같아서요 ㅎㅎ

2022-11-09 04:42 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/support/MentionAspect.java
> +            throw new RuntimeException(e);
좀 더 구체적인 Exception이었으면 좋겠어요!
커스텀을 만들기 애매하면 IllegalState나 IllegalArgument 같은 Exception은 어떨까요?

2022-11-09 04:42 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/support/MentionAspect.java
> +                .filter(field -> field.getName().equals("text"))
"text"도 상수화처리 되면 좋을 것 같아요 ㅎㅎ

2022-11-09 11:36 UTC, hyewoncc approved these changes
<img width="694" alt="image" src="https://user-images.githubusercontent.com/80666066/200819649-10e6489f-e5fd-471c-8aac-566e522d2bd3.png">

AOP 잘 몰라서 오프라인으로 코드리뷰를 빙자해 수업 받았는데 너무 좋았어요, 고마워요 최고 봄!! 👍 
코드가 훨씬 깨끗해졌네요 😁 수고하셨습니다~

2022-11-09 11:36 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/support/MentionAspect.java
> +    private void replaceMentionMemberInText(List<Field> fields, Object results, Map<String, String> memberMap)
메서드 이름만 봐서는 사람을 바꾸는 느낌이라 slackId -> username 임이 드러났으면 좋겠어요!

2022-11-09 11:36 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/support/MentionAspect.java
> +    private void replaceMentionMemberInText(List<Field> fields, Object results, Map<String, String> memberMap)
그리고 `final`이 빠졌네요 ㅎㅎ

2022-11-09 11:36 UTC, hyewoncc commented on backend/src/main/java/com/pickpick/support/MentionIdReplaceable.java
> +
내용물이 없다는 걸 확실히 해주기 위해  빈 줄 없애면 어떨까요?

2022-11-11 12:18 UTC, JangBomi commented on backend/src/main/java/com/pickpick/support/MentionAspect.java
> +        this.slackIdExtractor = slackIdExtractor;
처음에는 좀 더 복잡한 로직을 담고있으려고 했는데, 현재 상황에서는 util로서 존재해도 충분할 것 같네요! util로 바꿨습니닷 :)

2022-11-11 12:19 UTC, JangBomi commented on backend/src/main/java/com/pickpick/support/MentionAspect.java
> +                .filter(field -> field.getType().equals(List.class))
peek() 이 sonarqube에서 code smell 대상이라 해당 부분을 모두 제거했습니다!

2022-11-11 12:20 UTC, JangBomi commented on backend/src/main/java/com/pickpick/support/MentionAspect.java
> +            throw new RuntimeException(e);
ReflectionFailureException을 정의해서 사용했습니다!

2022-11-11 12:21 UTC, JangBomi commented on backend/src/main/java/com/pickpick/support/MentionAspect.java
> +    private void replaceMentionMemberInText(List<Field> fields, Object results, Map<String, String> memberMap)
`replaceMentionIdInText` 로 수정했고, final 키워드들도 다 붙였습니닷!

2022-11-11 12:27 UTC, JangBomi commented on backend/src/main/java/com/pickpick/support/MentionIdReplaceable.java
> +
없앴습니다!!!

2022-11-11 13:20 UTC, yeon-06 approved these changes
안녕하세요 봄~!
테스트 코드와 관련된건 별도의 태스크로 추가하겠다는 말씀을 듣고 approve 하겠습니다☺️
정말 간단한 수정 사항이 있는데 그 부분만 확인해주세요!

2022-11-11 13:20 UTC, yeon-06 commented on backend/src/main/java/com/pickpick/utils/SlackIdExtractUtils.java
> +public class SlackIdExtractUtils {
util로 바뀌었으니 private 기본 생성자도 추가하면 좋을 것 같아요 ㅎㅎ

2022-11-11 13:20 UTC, yeon-06 commented on backend/src/test/java/com/pickpick/message/support/SlackIdExtractUtilsTest.java
> +    private final SlackIdExtractUtils slackIdExtractUtils = new SlackIdExtractUtils();
util이니까 이제 new로 생성할 필요가 없겠네요!

2022-11-11 13:34 UTC, hyewoncc approved these changes
리뷰 반영하신 것 확인했어요! 저도 approve 할게요~ 
연로그가 남긴 변경사항 있어서 머지는 안하겠습니다, 수고했어요!

2022-11-11 15:04 UTC, JangBomi commented on backend/src/main/java/com/pickpick/utils/SlackIdExtractUtils.java
> +public class SlackIdExtractUtils {
앗,,, 빠르게 해버린다는게 꼼꼼히 살펴보지를 않았네요 😭 수정했습니다

2022-11-11 16:32 UTC, merged